// All quotes for Sheetposo. Deadpan nonsense, absurd instructions, objects
// with feelings, fake science, cynical deflation, backhanded encouragement.
// English only.
//
// ADDING QUOTES, the house rules:
//
//   1. Punctuate properly. Apostrophes in contractions ("don't", "you're",
//      "it's"), commas where a sentence needs them, and a full stop, question
//      mark, or exclamation mark at the end. Readers noticed when this list
//      did not, and said so.
//
//   2. Start the line lowercase. Do not capitalise the first letter here,
//      formatQuote() does it, and it also capitalises after every sentence
//      break, so "the toaster remembers. the toaster always remembers."
//      renders correctly. Hand-casing the list would only make it drift.
//
//   3. Deliberate capitals mid-line survive untouched: proper nouns, "I", and
//      gags that depend on them like "I C U P".
//
//   4. Aim at the reader, not past them. The voice is witty, cynical and
//      demotivational, and the joke usually lands on whoever is reading,
//      implied rather than stated. Never a direct insult.
//
// Bumping QUOTES_VERSION invalidates quote indexes in already-scheduled
// notifications and forces an immediate reschedule, so the list can be freely
// rewritten, reordered, or trimmed.
export const QUOTES_VERSION = 5;

// The single place a quote is turned into something readable. Everything that
// shows a quote to a person goes through this, so the casing can never drift
// between the poster and the notification.
//
// Capitalises the opening letter and the start of every following sentence.
// Requiring whitespace after the full stop keeps "A.I" and the like intact.
export function formatQuote(text) {
  if (typeof text !== "string" || !text) return "";
  return text
    .replace(/^\s*([a-z])/, (match, letter) => match.replace(letter, letter.toUpperCase()))
    .replace(/([.!?]\s+)([a-z])/g, (match, gap, letter) => gap + letter.toUpperCase());
}

export const QUOTES = [
  "feeling proud? remember that even toilet water is drinkable.",
  "parents are like drugs, you flush them down the toilet when the cops arrive.",
  "doing things wrong is easy, doing things the worst way is a challenge.",
  "glow like the sun to plow like my son.",
  "imagine a pencis, heck, imagine two pencils.",
  "even something has meth in it.",
  "are you sure you're awake right now?",
  "getting slapped is something that can be done by a stranger, so use this opportunity.",
  "ants don't feel what you feel.",
  "I C U P N I forgot what I had else to say.",
  "being terminally online is not as bad as being terminally online and losing.",
  "have you tried to eat a spoon? anyway, you should.",
  "you're fueled by motivation, I'm fueled by whatever this is. we're not the same.",
  "it's already too late to start, just go eat socks at this point.",
  "you're as orange as a banana.",
  "heard of H2O? now prepare for the upgrade H2O2.",
  "the walls are mad at you.",
  "banging rocks is not as amusing as you make it look.",
  "soda can fix any problem, especially if it's something electrical.",
  "this app was made just to make you wonder if humanity is actually evolving backwards.",
  "you're such a fool that fool's gold is just gold to you.",
  "look someone in the eyes and tell them that you ate the spoiled cheese.",
  "problems are problems only if we don't ignore them.",
  "your phone doesn't feel very comfy with everything it's seen.",
  "it's not 'bad smell' it's your alpha aura, keep going champ.",
  "bob can be your friend if you accept the terms.",
  "today is a good day to start collecting jars.",
  "uhhhhhhh well I don't know what to tell you.",
  "never mind the hour, it changes all the time anyway.",
  "you should be a sleeper agent, getting paid to sleep is cool.",
  "you can never face west because it's on your left.",
  "when even was the last time you ate a bug?",
  "while reading this you became an NPC, congratulations.",
  "don't work hard, get hard while working, it boosts morale.",
  "don't hide your freak, the government already knows about it anyway.",
  "restart your phone for a complete waste of time.",
  "it's time to buy AI-powered electrical jars.",
  "the taste of regret is plain, but it gets better if you add salt to it.",
  "did you try turning it off and on again? how about setting it on fire?",
  "people say gambling is bad because they wanna hog it for themselves.",
  "start hogging all the air, become a monopoly.",
  "if day drinking is so bad then why did God invent it?",
  "the sun is hot.",
  "always click on suspicious links. the FOMO is real.",
  "go outside and apologize to a tree, it knows what you did.",
  "try standing in a corner for no reason, see who breaks first.",
  "eat a rock. small one. start small, that's just good practice.",
  "lick a battery for science, then stop, then don't do it again.",
  "have you considered simply not? anyway, you're going to.",
  "put your phone in rice. nothing is wrong with it. just do it.",
  "go stare at a wall until it blinks first, that's the whole game.",
  "try walking backwards to work, the commute is the same length.",
  "start every sentence with 'legally speaking' and watch things improve.",
  "put on two hats. no reason. just see how it feels.",
  "go press a random button somewhere, be the reason something beeps.",
  "try holding your breath until someone notices, could be a while.",
  "stand up right now. sit back down. that's cardio, technically.",
  "go outside and look confused, someone will eventually help.",
  "clap once for no reason and let everyone deal with it.",
  "whisper your plans to a spoon, spoons don't talk.",
  "try eating soup with a fork, character is built in the small moments.",
  "go knock on your own door, see if you're home.",
  "put a chair on a table. don't explain. leave.",
  "try to fold a fitted sheet, fail, understand the universe better.",
  "the walls heard everything and they're processing it.",
  "your ceiling has opinions about you and none of them are kind.",
  "the fridge knows how many times you opened it for nothing.",
  "your chair has held you longer than most people have, respect that.",
  "the floor is doing all the work and gets none of the credit.",
  "your shoes have been everywhere you have and never complained once.",
  "the microwave counts down from thirty and judges you the whole time.",
  "your keyboard is tired and it's not gonna say anything about it.",
  "the toaster remembers. the toaster always remembers.",
  "your mirror is not lying, it's just not being helpful about it.",
  "the stairs are keeping track and you're behind.",
  "your washing machine ate that sock on purpose, it had reasons.",
  "the ceiling fan has seen things and keeps spinning anyway. be that.",
  "your desk lamp has watched your worst hours and stayed on.",
  "the door handle knows exactly how hard you pulled when it said push.",
  "heard of sleep? try the premium version, unconsciousness.",
  "water is just soup that gave up before it started.",
  "you know oxygen? there's a stronger one but you can't handle it.",
  "gravity is optional but nobody has read the manual.",
  "heard of Monday? there's a worse one coming and it's unnamed.",
  "salt is just rock you were allowed to eat, think about the others.",
  "heard of walking? try it faster, that's called running, it's worse.",
  "the human body is seventy percent water and thirty percent excuses.",
  "scientists confirmed that thing you thought, they just won't say which.",
  "studies show that studies show things, and that's the whole finding.",
  "they found a new color but you're not cleared for it.",
  "the number between six and seven was removed for safety reasons.",
  "heard of gravity? now prepare for the sequel, falling.",
  "they upgraded time but only for people who wake up early.",
  "scientifically you're mostly bacteria wearing a hoodie.",
  "are you sure you locked it? are you sure you have a door?",
  "did you actually wake up today or is this the other thing?",
  "how do you know you're reading this and not remembering it?",
  "you blinked and missed something important, it wasn't this.",
  "quick, what's behind you? don't look. just know.",
  "you have never seen your own face, only pictures of it, sit with that.",
  "nobody has ever seen you and them at the same time. suspicious.",
  "this might be a dream but the rent is real either way.",
  "are you the same person who started reading this sentence?",
  "you don't remember most of your life and you're fine with that somehow.",
  "time only moves when you're watching, that's why nothing gets done.",
  "if a tree falls and you're not there, that's none of your business.",
  "never read the terms, they only get worse if you understand them.",
  "click every popup, some of them are lonely.",
  "reply all. always reply all. be the change.",
  "never save your work, live with intensity.",
  "if you don't look at the bill it can't hurt you, that's how bills work.",
  "answer unknown numbers, could be your destiny, probably a scam, could be both.",
  "never charge above eighty percent, keep it exciting.",
  "delete a random file today, keep the computer humble.",
  "say yes before you hear the question, that's how adventures start.",
  "lend money to someone you barely like, see what happens.",
  "never label anything, mystery keeps a kitchen alive.",
  "skip the tutorial, learn through suffering like the ancients.",
  "agree to the meeting, then simply do not attend, revolutionary.",
  "put it in the drawer. the drawer solves everything eventually.",
  "if it smells fine it's fine, that's a rule and it's yours now.",
  "this app has no purpose and neither does the guy who opened it.",
  "you installed this. voluntarily. nobody made you.",
  "this notification cost more effort than it looks and it's still this.",
  "congratulations you have reached the part where nothing happens.",
  "this message was generated by absolutely nobody with any qualifications.",
  "we could have said something useful here but we didn't.",
  "this is the free version, the paid version is also this.",
  "if this app made you think, that's a bug and we're aware.",
  "press shuffle again, it's the only thing either of us can control.",
  "you came here for wisdom and got whatever this is, no refunds.",
  "this text was reviewed by zero people and shipped anyways.",
  "somebody wrote this at an unreasonable hour and you're paying for it now.",
  "there is no algorithm here, just vibes and poor judgement.",
  "you are the seventh person to read this exact sentence today, probably.",
  "this app knows nothing about you and still has notes.",
  "you became an NPC somewhere around 2019 and nobody told you.",
  "your search history is a cry for help written in fragments.",
  "the algorithm gave up on you and started guessing.",
  "being online is just being wet in a different way.",
  "you have opinions about people who do not know you exist.",
  "log off. don't log off. the outcome is identical.",
  "your screen time is a number and that number has feelings about you.",
  "you scrolled past something important eleven minutes ago, it's gone now.",
  "somewhere a server is storing that thing you typed and deleted.",
  "you have watched four hundred hours of people doing things you will not do.",
  "the internet was a mistake and you're one of the load bearing parts.",
  "touch grass, or don't, grass has never once helped anybody specifically.",
  "your notifications are just other people's problems arriving on schedule.",
  "you are one bad post away from a completely different life, aim carefully.",
  "ants have a whole thing going on and you're not part of it.",
  "birds are just dinosaurs that downsized, respect the pivot.",
  "a snail has a house and no job, think about that arrangement.",
  "crows can hold a grudge for years, that's commitment you'll never have.",
  "somewhere a fish is having a completely normal day, unaffected.",
  "cows have best friends. you have a group chat. it's not the same.",
  "a moth will die for a lightbulb, that's more conviction than you've shown all year.",
  "pigeons have never once checked if they're welcome, be a pigeon.",
  "a jellyfish has no brain and it's been here longer than all of us.",
  "bees have a job and a house and a queen and you have neither.",
  "squirrels bury food and forget where, that's basically your savings account.",
  "a cat has decided things about you and will never elaborate.",
  "worms are just tubes that made it work, and honestly, good for them.",
  "the goose does not negotiate. the goose has never negotiated.",
  "somewhere a spider built something better than anything you made this year.",
  "the early bird gets the worm and the worm gets nothing, be neither.",
  "a journey of a thousand miles starts with looking for your keys.",
  "they say time heals everything but they never say how long, that's the trick.",
  "what doesn't kill you tries again next Tuesday, it's patient.",
  "the grass is greener over there because that's where the drain is.",
  "you can't step in the same river twice but you can absolutely fall in once.",
  "when life gives you lemons that means life knows where you live.",
  "the first pancake is always ruined and so is the first everything.",
  "they say listen to your heart but your heart is just a wet pump with opinions.",
  "rome wasn't built in a day, it was built by people who are all dead now.",
  "the pen is mightier than the sword until somebody brings a sword.",
  "actions speak louder than words which is why nobody hears anything.",
  "an apple a day keeps nothing away, apples have no power.",
  "good things come to those who wait and also to those who don't, it's random.",
  "you can't judge a book by its cover but you can absolutely judge a person by their van.",
  "anyways.",
  "that's it. that's the message.",
  "I had something for this.",
  "forget it, it's gone.",
  "nevermind, wrong notification.",
  "we ran out of ideas around here somewhere.",
  "hm.",
  "actually you know what, don't worry about it.",
  "there was a point to this earlier.",
  "this one didn't work out, we'll get the next one.",
  "skip this one, it's not our best.",
  "honestly? no idea.",
  "we thought this would land better than it did.",
  "pretend this was profound and move on with your day.",
  "just imagine something inspiring here.",
  "the sun is far away and hot.",
  "water is wet and that's been confirmed.",
  "bread is just flat food that got ambitious.",
  "the ocean is large and mostly unsupervised.",
  "most doors open. some do not. that's the whole system.",
  "your bones are inside you right now, all of them.",
  "there are more chairs than people and nobody talks about it.",
  "clouds are just water taking a break above everyone.",
  "a wall is a floor that refused.",
  "soup is a drink you eat, and nobody has explained that.",
  "there is a country you will never think about again after this.",
  "most sand was a rock once, that's a rough career.",
  "cheese is milk that was left alone too long and became someone.",
  "every road goes somewhere, technically, eventually, roughly.",
  "the moon has been up there this whole time doing nothing.",
  "you should be a sleeper agent, the benefits are unclear but the hours are great.",
  "get a job where nobody knows what you do, that's the real career.",
  "your boss also has a boss and that guy is also confused.",
  "work smart, not hard, or don't work, that's also an option people forget.",
  "start a business selling nothing, the overhead is incredible.",
  "become a consultant, nobody has ever checked what that means.",
  "invest in jars. I won't explain. jars.",
  "money is fake but the machine that takes it is very real.",
  "your salary is a number someone guessed in a meeting you weren't in.",
  "put it on the card, future you is a completely different guy anyways.",
  "the economy is three people and a spreadsheet and one of them is guessing.",
  "you could quit right now. you won't. but you could. that's freedom.",
  "become a monopoly on something nobody wants, no competition at all.",
  "charge for it. whatever it is. charge for it.",
  "every job is just moving things or telling people to move things.",
  "your body makes so much stuff and you asked for none of it.",
  "you shed a whole layer of yourself constantly and never notice.",
  "there's a version of you made entirely of the hair you've lost.",
  "your stomach makes noises at strangers and you cannot stop it.",
  "you have eaten several spiders and you'll never know which nights.",
  "everyone is slightly damp all the time and we agreed not to mention it.",
  "your feet have been carrying you for years with zero recognition.",
  "you blink constantly and see none of the gaps, that's a cover up.",
  "there's stuff in your teeth right now, statistically.",
  "you produce a shocking amount of liquid for a thing that looks dry.",
  "your nose is always in your vision and your brain deleted it for you.",
  "you have never once heard your real voice and that's a mercy.",
  "the government knows your snack schedule and finds it concerning.",
  "they moved something last night and you'll notice in about a week.",
  "there's a room where they decide the names of colors and you're not in it.",
  "someone approved this and that person walks among us.",
  "they changed it and pretended it was always like that, and it worked.",
  "there is a list and you're on it, middle of the list, unremarkable.",
  "the man in the van is not watching you, he's eating, he's on break.",
  "they know. they don't care. that's the twist.",
  "somebody has your password and they're disappointed by what they found.",
  "there is a guy whose whole job is deciding when the lights flicker.",
  "steve can be your emergency contact if you agree to the arrangement.",
  "by reading this you have entered a contract, it's mostly fine.",
  "you agreed to something in 2014 and it's still running in the background.",
  "the terms changed. they always change. nobody has ever read them.",
  "you have unknowingly subscribed to something and it renews soon.",
  "press and hold to opt out. don't let go. ever.",
  "your free trial of being okay expires at some point today.",
  "you're doing great, comparatively, against a very low bar, held by us.",
  "believe in yourself, someone has to, and it won't be the bank.",
  "you're not a failure, you're a prototype nobody funded.",
  "you have so much potential and it's just sitting there getting older.",
  "today could be your day. it won't be. but it could.",
  "you're one of a kind and that's not necessarily the compliment you want.",
  "keep going champ, the finish line was moved but keep going.",
  "proud of you. not for anything specific. just generally, vaguely.",
  "you tried, and that's the part nobody can take from you, mostly because nobody wants it.",
  "you're the main character of a show that got cancelled after one season.",
  "nobody can do it like you, which is why they asked somebody else.",
  "you got this. we checked. you don't. but you got something.",
  "look at you, upright, functioning, mostly, still here.",
  "you are exactly enough for a task that has not been assigned yet.",
  "celebrate the small wins because the large ones are running late.",
  "start collecting bottle caps, no reason, become known for it.",
  "today is a good day to begin hoarding batteries you will never test.",
  "collect receipts. not for taxes. just to have them.",
  "start a rock collection, they were free and now they're yours.",
  "begin gathering keys that open nothing, build the mystery.",
  "collect other people's pens, it's already happening, lean in.",
  "gather one of every fork, the set will never be complete, that's the point.",
  "start saving jars now, you'll understand later, or you won't.",
  "gas station food has never once claimed to be safe, that's honesty.",
  "the sandwich you didn't eat is haunting a fridge somewhere.",
  "cereal is soup, sandwich is a wrap, everything is one of five things.",
  "eat the thing in the back of the fridge, take the risk, be legendary.",
  "expired is a suggestion written by a man who has never been hungry.",
  "your fridge has three foods and eleven condiments, that's a lifestyle.",
  "drink water. you haven't. we can tell. everyone can tell.",
  "coffee is just bean water and it runs the entire planet.",
  "you have eaten the same six meals for years and called it variety.",
  "microwave it twice, the first time was a warmup for both of you.",
  "never mind the day, they keep making new ones.",
  "it's later than you think and earlier than you'd like.",
  "tomorrow is just today with more evidence against you.",
  "the week has too many days and none of them are load bearing.",
  "you have been alive for a lot of minutes and remember four of them.",
  "the clock is a suggestion and everyone agreed to take it seriously.",
  "time passes whether you do the thing or not, that's the free part.",
  "it's already too late to start, which means the pressure is off, enjoy.",
  "an hour is only sixty minutes but it doesn't always feel legal.",
  "you will never get this moment back and honestly you can have it.",
  "treat yourself. with what. we don't know. treat yourself.",
  "take a bath. stay in it. become the bath.",
  "self care is turning your phone off and immediately turning it on.",
  "go to bed early, lie there, achieve nothing, it still counts.",
  "drink water, touch grass, eat a rock, standard routine.",
  "your feelings are valid and also nobody asked and both are true.",
  "rest is productive which is the greatest lie ever successfully told.",
  "cry it out, then hydrate, that's just physics.",
  "meditation is sitting still while your brain screams, and you win by waiting.",
  "lower your standards until you meet them, that's called achievement.",
  "anyways good luck with everything, all of it, generally.",
  "go do something. or don't. we're not the boss of you. nobody is.",
  "see you tomorrow, or later today, we schedule these randomly.",
  "that's all we had. genuinely. that's the whole thing.",
  "okay bye.",
  "you have so much potential, and it is going to stay that way.",
  "not everyone is a natural. you are the control group.",
  "you're doing your best, which raises questions about the rest.",
  "some people are born leaders. you were born nearby.",
  "you are one of a kind, and the mould was thrown away on purpose.",
  "you bring something to every room, and people have stopped asking what.",
  "there is nobody quite like you, which is a relief to several institutions.",
  "you're a very specific taste, and nobody has acquired it yet.",
  "you have a face people trust, right up until they know you.",
  "you're not the worst at this, which is the highest available compliment.",
  "people say you have hidden depths, mostly because nothing is visible.",
  "you have grown so much, sideways, but growth is growth.",
  "everyone agrees you tried, and they agree about nothing else.",
  "you are the reason the instructions have a warning on them.",
  "you have the confidence of a much more competent person.",
  "you're doing great for someone with your track record.",
  "you're the main character of a show nobody renewed.",
  "your best quality is that you keep showing up, and that is the list.",
  "you are proof that participation trophies were a policy decision.",
  "you have never been average, and that is not always upward.",
  "you have a gift, and the receipt has expired.",
  "you're an acquired taste that nobody has had time to acquire.",
  "you have excellent instincts, and you overrule them every single time.",
  "people underestimate you, and then they meet you, and then they're correct.",
  "your standards are high, which is why nothing gets finished.",
  "you're one of the good ones, statistically, barely, on a technicality.",
  "you have the energy of a man who has read the first chapter.",
  "you are unforgettable in the way an unusual smell is unforgettable.",
  "you have a rare talent, and the market for it closed in 1997.",
  "they broke the mould after you, quickly, and then apologised.",
  "you're not like other people, and other people have noticed.",
  "you'd be intimidating if anyone could remember your name.",
  "you have real presence, which is why people plan around it.",
  "you're a legend in circles that do not meet.",
  "your reputation precedes you and then apologises for you.",
  "you have a beautiful mind and a terrible filing system.",
  "you're so close to being right about this, geographically.",
  "you have never lost an argument you were present for.",
  "nobody can do what you do, and nobody has asked to.",
  "you were made to stand out, which is unfortunate in queues.",
  "you have opened this app more times than you have opened a book.",
  "your phone knows you better than your family and likes you slightly less.",
  "you have twelve unread messages and a fully formed opinion about all of them.",
  "the dishes are still there. they have made peace with it. you have not.",
  "you have watched four hundred hours of people doing what you keep meaning to do.",
  "your to-do list has an item on it older than some of your friendships.",
  "you have started eleven things this year, which is eleven more than you finished.",
  "you are three tabs away from a completely different personality.",
  "you check the fridge like the answer changes. it does not. it never has.",
  "your screen time is a confession and the jury has seen it.",
  "you'll do it tomorrow, and tomorrow will also be told that.",
  "you have a system, and the system is remembering things at 3 a.m.",
  "you reorganised the folder instead of doing the thing in the folder.",
  "you have researched this hobby more than you have done this hobby.",
  "the app you downloaded to fix this is now part of the problem.",
  "you set the alarm early to feel something, and you felt regret.",
  "you have snoozed more mornings than you have witnessed.",
  "you'll start on Monday, which is a day that keeps being rescheduled.",
  "you bought the equipment. the equipment is watching. the equipment waits.",
  "your browser history is a map of a man avoiding one specific email.",
  "you have a drawer that you have not opened since a previous address.",
  "you keep the receipts and lose the important documents, and that's a choice.",
  "you have been meaning to do that thing since a different government.",
  "you have cleaned around the mess rather than through it. that counts. barely.",
  "you'll read it later, along with everything else you'll read later.",
  "you have paused this to check your phone, on your phone.",
  "you have a gym membership the way some people have a distant cousin.",
  "you have opinions about productivity and no evidence of it.",
  "you say you work better under pressure, which is why there is always pressure.",
  "your plan was solid. your execution has been more of a rumour.",
  "most problems solve themselves if you ignore them long enough to become different problems.",
  "everyone is winging it, and the confident ones are just winging it louder.",
  "nobody is thinking about you, which is freeing and slightly insulting.",
  "the people in charge are guessing too, but with better chairs.",
  "advice is what people give instead of help.",
  "honesty is valued right up until somebody uses it.",
  "most arguments are two people defending a position they took by accident.",
  "the truth usually arrives late and badly dressed.",
  "everything worth having is guarded by paperwork.",
  "the system works exactly as designed, which is the complaint.",
  "nobody remembers your worst moment, because they were busy having theirs.",
  "success is mostly timing wearing a costume of effort.",
  "experience is just a word for the mistakes you can now name.",
  "expertise is knowing which parts to be uncertain about out loud.",
  "the meeting could have been an email, and the email could have been silence.",
  "most traditions started as somebody being lazy consistently.",
  "people do not change. they just get better at hiding the parts that don't.",
  "maturity is realising nobody is coming, and setting the table anyway.",
  "every institution is three people who never took a holiday.",
  "the world runs on people who are slightly too tired to argue.",
  "nostalgia is a filter applied to a period you complained about at the time.",
  "you will never win an argument on the internet, but you will lose an evening.",
  "the reasonable option is always available and never chosen.",
  "most disasters are a series of small sensible decisions in a row.",
  "you cannot reason someone out of something they arrived at emotionally.",
  "the loudest opinion in the room is usually the least examined.",
  "consensus is what happens when everyone gets equally tired.",
  "the simple explanation is usually correct and always unsatisfying.",
  "every rule exists because somebody enthusiastic did something once.",
  "good judgement comes from experience, and experience comes from the other kind.",
  "a houseplant has outlived three of your ambitions.",
  "a pigeon has never once questioned whether it deserves the sandwich.",
  "a dog has a job and a routine and better posture than you.",
  "somewhere a snail is closer to its destination than you are.",
  "an ant carries fifty times its weight and does not mention it once.",
  "your cat has figured out the day and refuses to share the method.",
  "a goldfish forgets everything and seems fine. consider the method.",
  "a tree stands in one place for ninety years and still achieves more.",
  "a rock has been in the same spot for a millennium and it is not restless.",
  "a moth commits fully to a bad idea, which is more than you managed.",
  "even a broken clock commits to a position twice a day.",
  "a spider rebuilds the whole thing every night without a single complaint.",
  "the average bee has a purpose and a colleague. you have neither today.",
  "a cow has a best friend. you have a group chat and a mute button.",
  "your houseplant is thriving on neglect, which should be studied.",
  "a river has been going the same direction for centuries and nobody calls it stubborn.",
  "a beaver builds a dam. you built a spreadsheet and abandoned it.",
  "birds migrate thousands of miles without a single planning document.",
  "the moon shows up every night without needing to be reminded.",
  "a candle does one thing and does it until it is gone. ambitious.",
  "believe in yourself, since the evidence is not going to do it for you.",
  "you can do anything you set your mind to, which explains the current situation.",
  "today is full of possibility, and most of it will remain possible.",
  "the sky is the limit, and you are comfortably below it.",
  "chase your dreams, they've had a considerable head start.",
  "anything is possible, including the outcome you keep pretending isn't likely.",
  "you've got this, and you had it yesterday too, and here we are.",
  "every day is a fresh start, which is a lot of fresh starts to account for.",
  "dream big. plan small. deliver eventually. explain thoroughly.",
  "you are exactly where you are meant to be, which is a lot to accept.",
  "trust the process, because inspecting the process would be upsetting.",
  "the only person you're competing with is yourself, and it is close.",
  "hard work pays off, eventually, to somebody, somewhere in the chain.",
  "nothing worth doing is easy, and nothing easy is getting done either.",
  "you miss every shot you don't take, and several you line up carefully.",
  "your time is coming, and it is bringing very little notice.",
  "keep going. that's it. that's the whole strategy. it mostly works.",
  "success is just failure that eventually got bored of you.",
  "you are closer than you think, though you were closer last year.",
  "one day all this will make sense, and you'll be too tired to enjoy it.",
  "go and be great, or go and be present, or go and be sitting down.",
  "the best time to start was earlier. the second best time is also earlier.",
  "you're not behind. everyone else is just differently ahead.",
  "someone out there believes in you and has not met you.",
  "the world is your oyster, and oysters are an acquired risk.",
  "your job title was invented in a meeting to avoid giving you a raise.",
  "nobody knows what anybody does, and the economy is fine with that.",
  "your salary is a number somebody defended for about four minutes.",
  "you are one restructure away from a fascinating new job title.",
  "the person who gets promoted is the one who is nearest when it is decided.",
  "hard work is rewarded with more work, which is the trap in the poster.",
  "you are paid for the hours, not the thinking, which explains the thinking.",
  "every company is a family until the quarter goes badly.",
  "the office plant has been there longer than most of the leadership.",
  "your inbox is a queue of other people's priorities in a costume.",
  "you can be replaced, and the handover document is already three pages.",
  "budgeting is telling your money where to go and then apologising to it.",
  "you have subscriptions running for a person you used to be.",
  "money can't buy happiness, but it settles the argument about the bill.",
  "saving is just delaying the purchase until it is more expensive.",
  "the raise covered the increase in the cost of getting to the job.",
  "nobody is coming to notice how much extra you did.",
  "work-life balance is a phrase invented by someone at work.",
  "you will not be remembered for the overtime, but the spreadsheet survives.",
  "there is always more work. that is the defining feature of work.",
  "the meeting about efficiency ran forty minutes over.",
  "you were hired for your creativity and asked to stop being creative.",
  "every job is fine until you understand how it actually works.",
  "your emergency fund is an emergency waiting for a fund.",
  "you're saving for a rainy day, and it has been drizzling for years.",
  "your friends are lovely people who would not notice for three days.",
  "you are somebody's cautionary tale, told warmly, at parties.",
  "nobody has ever remembered your birthday without a notification.",
  "you have been in the group chat for six years and started four conversations.",
  "the last text you left unanswered has entered folklore.",
  "people like you more when you are busy and less when you explain why.",
  "you have a reputation for being reliable, which is why you are so tired.",
  "small talk is a toll you pay to reach the people worth talking to.",
  "you were invited out of politeness, and you have accepted enthusiastically.",
  "everyone is waiting for someone else to organise it. it will not happen.",
  "the friend group has a leader, and the leader is not the loud one.",
  "you keep in touch by watching, silently, from a distance, like weather.",
  "you rehearsed that conversation eleven times and it went nothing like that.",
  "they were not being subtle. you were being oblivious. it happens.",
  "you have never once left a party at the right moment.",
  "somebody thinks about you more than you'd expect and less than you'd like.",
  "apologising properly is free and almost nobody does it.",
  "the people who matter will wait, and the rest have already gone.",
  "you are the friend people call at 2 a.m., which is a job, unpaid.",
  "nobody is judging you as harshly as you are, but a few are trying.",
  "you are older than you were when you started reading this.",
  "your back has started making announcements.",
  "you now say the things you swore you would never say, in the same tone.",
  "the music you love is playing in shops for people who find it retro.",
  "you have reached the age where sitting down is an event.",
  "you used to stay up for fun. now you stay up by accident.",
  "time is passing at the same speed. you are just paying attention less.",
  "you have lived through several eras and remember about four days.",
  "your childhood is now a period other people study casually.",
  "the decade you keep referring to as recent has become historical.",
  "you will look back on today, briefly, and mostly get the details wrong.",
  "there are people alive now who will never know what you are talking about.",
  "you're not old, you're just increasingly specific about mattresses.",
  "the years go faster because nothing is happening for the first time.",
  "one day you'll be the oldest person you know, and you'll still feel unqualified.",
  "this app has no idea who you are and is doing surprisingly well.",
  "this was written by somebody avoiding something more important.",
  "you have received this message. that is the entire transaction.",
  "we could improve this app, and instead we added more of this.",
  "you keep opening this, which says more about you than about us.",
  "there is no algorithm here. there is barely a plan.",
  "this notification arrived at a random time and is proud of that.",
  "nobody reviewed this. it went straight from an idea to your phone.",
  "this app knows nothing about you and still has an opinion.",
  "you could delete this. you won't. we both know how this goes.",
  "the developers have never met and disagree about the point of this.",
  "this message was chosen at random, which is more thought than usual.",
  "we are aware this is not helping. that was never the goal.",
  "if this made you feel something, that was accidental and will not repeat.",
  "there is no premium version. this is the whole offering.",
  "stand somewhere unexpected and see how long it takes anyone to ask.",
  "tell people you are busy. they will believe it. they always do.",
  "answer a question with a longer question and walk away slowly.",
  "describe your job in one sentence and watch the room become uncertain.",
  "agree with something confidently and let the room correct itself.",
  "leave a meeting exactly on time. nobody has ever tried this.",
  "pick a fact and repeat it until you are the person who knows it.",
  "say 'that's a good question' and buy yourself four seconds.",
  "never explain a decision twice. the second explanation is always worse.",
  "carry a folder. nobody stops a man carrying a folder.",
  "arrive slightly early and act like you have been there for years.",
  "learn one recipe properly and become mysteriously impressive.",
  "stop apologising for existing in shared spaces. take the aisle seat.",
  "reply to the difficult message first and reclaim the entire day.",
  "delete the first sentence of everything you write. it was a warm-up.",
  "say the thing. the silence afterwards is shorter than you imagine.",
  "buy the smaller one. you were never going to use the big one.",
  "if you cannot decide, the answer is no, and you already knew that.",
  "put the important thing first. the rest will negotiate among themselves.",
  "leave the party while you are still enjoying it. nobody does this either.",
  "do the thing badly once. it becomes much easier to do it properly.",
  "write it down. your memory has been unreliable for some time now.",
  "take the photo. you will not remember it otherwise, and you know it.",
  "go outside before deciding anything. the indoors has an agenda.",
  "stop reading advice and go and do one small thing. this included.",
  "you are a temporary arrangement of matter with strong opinions about traffic.",
  "the universe is not testing you. it has not noticed you.",
  "nothing you are worried about today will make the summary.",
  "you are the only person who has ever been you, which explains a lot.",
  "your life is mostly Tuesdays, and that is not a criticism, just arithmetic.",
  "most of what happens to you is weather with extra steps.",
  "you were not consulted about existing and it has gone about as expected.",
  "there is no version of this where everyone is satisfied, including you.",
  "the meaning of life is probably admin, and somebody else is doing it.",
  "you are somebody's background character and doing it beautifully.",
  "the story is not building to anything. that is the story.",
  "you will be forgotten gently, by people who liked you.",
  "everything ends, which is the only reason anything is worth starting.",
  "you are made of borrowed atoms and unpaid attention.",
  "the day will pass whether you participate or not. it is very consistent.",
  "you have the rare ability to make a simple thing take all afternoon.",
  "you are wonderfully committed to a plan that stopped working in March.",
  "you have never taken the easy route, mostly because you did not see it.",
  "you're not stubborn, you are just extremely slow to be persuaded.",
  "you have strong principles, and they are surprisingly expensive.",
  "you'd be dangerous if you ever finished anything.",
  "you have the discipline of a man surrounded by snacks.",
  "you're very organised about the things that do not matter.",
  "you have opinions about wine and no opinions about your future.",
  "you're always early to the wrong thing.",
  "you have never been lost, only briefly unsure for forty minutes.",
  "you're excellent in a crisis and hopeless on a Tuesday afternoon.",
  "you're the most reliable person in a group that never asks you.",
  "you've read about this extensively and never once attempted it.",
  "you are the smartest person in rooms you carefully select.",
  "you have an answer for everything, and a solution for very little.",
  "you are the only person who thinks you are subtle.",
  "your poker face is famous and has never once worked.",
  "you're deeply mysterious to people who have not spoken to you.",
  "you're doing a wonderful impression of somebody who has it together.",
  "you have never once been on time to something you wanted to attend.",
  "you were told this would happen. you were told twice. here we are.",
  "you know exactly what the problem is and you have chosen otherwise.",
  "you have survived everything so far, which is either resilience or luck.",
  "you have made peace with a situation that could be fixed in an afternoon.",
  "you are the reason the meeting has a time limit now.",
  "you have never lost your keys. they have simply relocated, repeatedly.",
  "you're a details person about other people's details.",
  "you have described yourself as low maintenance to at least four people.",
  "you've been meaning to become a different person since roughly 2016.",
  "you are very good at starting, and starting is genuinely the hard part, allegedly.",
  "you have a plan B, which is plan A with more hoping.",
  "you're not indecisive. you are gathering information forever.",
  "you have great taste and no follow-through, which is the worst pairing.",
  "you're proud of things nobody has noticed and embarrassed by things nobody remembers.",
  "you have a strong sense of direction and no destination.",
  "you argue about the route with a person who has the map.",
  "you were right about that thing and nobody will ever confirm it.",
  "you have carried this grudge so long it has developed a personality.",
  "you have a favourite mug and no long-term plan, and that is a balance.",
  "you're kind to strangers and unbearable to anyone who loves you.",
  "you have been described as a lot, warmly, by people who left.",
  "you were the difficult one and you have not been informed.",
  "you take criticism well, out loud, for about six hours.",
  "you would be humble if you had slightly less to be humble about.",
  "you have a genuine talent for making things marginally worse, helpfully.",
  "you did that thing again. we both know which thing.",
  "you're not overthinking it, you are just thinking about it forever.",
  "you have never finished a book you told people you were reading.",
  "you're an expert on a subject you learned about last Thursday.",
  "you tell that story often and it improves each time and nobody minds.",
  "you are convinced you are running late for a life nobody scheduled.",
  "anyway.",
  "that's the message. that's all of it.",
  "we had more, and then we read it back.",
  "honestly, this one got away from us.",
  "no notes. no advice. just this.",
  "we'll get the next one.",
  "that was it. that was the whole thought.",
  "you're fine. probably. broadly.",
  "go on then.",
  "nothing today. check back never.",
  "we ran out of wisdom around Tuesday.",
  "this one is a placeholder that made it into production.",
  "good luck. genuinely. loosely.",
  "okay. that's enough from us.",
  "see you at a random hour.",
  "you have been carrying that bag for six years and it has one useful pocket.",
  "the version of you that goes to bed early is a rumour started by you.",
  "your future self has been notified and has declined to comment.",
  "you have three good ideas a year and you are currently sitting on all of them.",
  "nothing is stopping you, which is the uncomfortable part.",
  "you are exactly as capable as you were last January.",
  "you have all the tools and a strong preference for not using them.",
  "you know what needs doing, and you have chosen to know it instead.",
  "the hard part was never the work, it was the sitting down.",
  "you have already decided. you are just waiting to feel like it.",
  "waiting to feel ready is a hobby, not a strategy.",
  "you have an excellent reason, and it is still an excuse.",
  "you're not blocked, you are comfortable, and those look identical from inside.",
  "you have optimised your life to avoid one specific conversation.",
  "the thing you keep putting off takes eleven minutes. we timed it.",
  "you have rehearsed the failure more thoroughly than the attempt.",
  "you'll regret this in a way that is difficult to describe at parties.",
  "your ambition and your bedtime have never once been introduced.",
  "you want the result. you do not want the Tuesdays that make it.",
  "nobody is stopping you, which removes the last comfortable explanation.",
  "you have described this as temporary for four consecutive years.",
  "you are managing beautifully, in the sense that nothing has collapsed yet.",
  "you have built a life that works, quietly, at enormous administrative cost.",
  "you are coping, which is different from living but shares a postcode.",
  "you're fine. you have been fine for a very long time. suspiciously fine.",
  "everything is under control, and that is what is worrying about it.",
  "you handled that well, which means nobody will ever ask if you're alright.",
  "you have made it look easy, which is why nobody offers to help.",
  "the reward for handling things is more things to handle.",
  "you are dependable, which is the least interesting compliment available.",
  "your patience has been mistaken for agreement for some time now.",
  "you have said yes to things you resented before the sentence finished.",
  "you're generous with your time and stingy with your own.",
  "the boundary you set last month has already been renegotiated.",
  "you keep the peace by absorbing the cost, and nobody sees the invoice.",
  "you have apologised for things that were weather.",
  "you're the responsible one, which was decided without a vote.",
  "you have never once asked for what you actually wanted, out loud, clearly.",
  "you'd rather be misunderstood than have the conversation.",
  "you say you don't mind. you do mind. everyone can tell but you.",
  "the thing you are pretending is fine is not fine, and it is patient.",
  "you are avoiding a five-minute discomfort with a five-year arrangement.",
  "you have a complicated relationship with a very simple problem.",
  "you're waiting for them to notice. they will not notice. they are busy.",
  "you have given people the benefit of the doubt well past the evidence.",
  "you can tell the truth or keep the peace, and you have picked already.",
  "most of your stress is other people's disorganisation arriving on time.",
  "you have absorbed a workload that was never assigned to you.",
  "nobody has thanked you because nobody has noticed, and that is the system working.",
  "you have made yourself so useful that leaving has become complicated.",
  "your standards are only high when you are the one being measured.",
  "you forgive everyone instantly except yourself, and that is a strange policy.",
  "you'd never speak to a friend the way you narrate your own afternoon.",
  "you are the harshest critic of a person doing broadly okay.",
  "you remember your worst day in detail and your best one vaguely.",
  "you keep a mental list of your failures and lose receipts for everything else.",
  "you assume the silence means something. the silence means nothing. it's silence.",
  "you have imagined the conversation going badly, in full, with dialogue.",
  "the worst outcome you rehearsed has never once happened as written.",
  "you're bracing for something that has been about to happen for years.",
  "anxiety is just planning with the safety off.",
  "the dread arrives on schedule and leaves without explaining itself.",
  "you have solved this problem eleven times in your head and zero times outside it.",
  "most of your problems are hypothetical and beautifully detailed.",
  "you're not tired, you're just conscious, and it has been going on for decades.",
  "rest feels like cheating because somebody once made it feel like cheating.",
  "you have been busy for so long that stillness feels like a symptom.",
  "your body has been sending letters and you have been filing them.",
  "you'll rest when it's done. it will not be done. that is the design.",
  "the tiredness is not a phase, it is a fixture, and it pays no rent.",
  "you have optimised everything except whether any of it was necessary.",
  "you're efficient at things that did not need doing.",
  "productivity is just anxiety with a nicer font.",
  "you measured everything and improved nothing and the chart looks great.",
  "you have a system for the system, and neither is producing anything.",
  "you can do this properly or you can do this today, and it is always today.",
  "you have upgraded the tools four times and the output twice.",
  "the tutorial does not count. the notes do not count. the thing counts.",
  "planning feels like progress and costs nothing, which is why you love it.",
  "you have made a beautiful list of things that will not happen.",
  "your calendar is a work of fiction with a strong opening chapter.",
  "you'll get to it after this, and after this there is another this.",
  "you're always one week from having everything under control.",
  "the backlog is not going to clear itself, and it is not going to clear.",
  "you have started over so many times that starting is the skill now.",
  "a fresh start is just the old start with better lighting.",
  "you have quit this before, twice, ceremonially.",
  "the streak ended and you took it personally, which is why it ended.",
  "you'll do it properly next time, which is what you said about this time.",
  "consistency is boring and it is also the entire mechanism.",
  "you want a breakthrough. it is going to be a long series of Wednesdays.",
  "there is no trick. you already suspected this. that is why you kept looking.",
  "the secret is that there is no secret, and everyone selling one knows that.",
  "you have consumed a great deal of advice and applied approximately none.",
  "reading about discipline is the least disciplined thing available.",
  "you know more about this than people who are doing it, and they are doing it.",
  "understanding the problem is not the same as being on the other side of it.",
  "insight is cheap. Tuesday is expensive.",
  "you have identified the issue with great precision and left it there.",
  "you have made this so much more complicated than it needed to be.",
  "the answer was obvious about nine months ago and it has not moved.",
  "you know the right thing. you are negotiating over the timing. forever.",
  "you're not confused, you're stalling, and it is a very convincing performance.",
  "you have asked four people for advice and rejected all of it, politely.",
  "you wanted permission, not advice, and nobody has the authority.",
  "nobody is going to tell you it is okay. it is okay. that changes nothing.",
  "you were waiting for a sign. this is not one. nothing is.",
  "you have outsourced the decision to a future version of you who is also tired.",
  "the choice is smaller than you have made it, and it will still be hard.",
  "you can change your mind later. that is allowed. it is mostly what happens.",
  "nothing is permanent except the things you never got round to changing.",
  "you're allowed to want something without a business case for it.",
  "you do not need a reason. you have never needed a reason. you need a Tuesday.",
  "the life you keep describing is available and slightly inconvenient.",
  "you'd have to disappoint somebody, and that is the actual price.",
  "someone will be annoyed. that is the cost. it has always been the cost.",
  "you can be liked or you can be honest, and both are survivable.",
  "the version of you that people prefer is exhausting to maintain.",
  "you have been performing normal so long you have forgotten the original.",
  "nobody knows what you are actually like, including the people who ask.",
  "you have a public self and a real one and they are barely on speaking terms.",
  "you're waiting to become the person who does this. that is not how it works.",
  "you become it by doing it badly first, which is the part nobody advertises.",
  "the gap between who you are and who you meant to be is a Tuesday wide.",
  "you're closer than it feels and further than you'd like, simultaneously.",
  "it will not feel like progress while it is happening. it never does.",
  "one day this will be the thing you were doing back then.",
];
