// All quotes for Sheetposo. Deadpan "bullshit wisdom": fake-profound setups
// that collapse into nonsense, plus lowercase shitpost one-liners. English only.
//
// Authored lowercase so notification bodies read as casual as the poster does
// (the poster also lowercases at render time).
//
// Bumping QUOTES_VERSION invalidates quote indexes in already-scheduled
// notifications and forces an immediate reschedule, so the list can be freely
// rewritten, reordered, or trimmed.
export const QUOTES_VERSION = 3;

export const QUOTES = [
  "feeling proud? remember that even toilet water is drinkable.",
  "parents are like drugs, you flush them down the toilet when the cops arrive.",
  "doing things wrong is easy, doing things the worst way is a challenge.",
  "you are a miracle of biology, and biology is mostly wet tubes screaming.",
  "every morning your skeleton wakes up inside you and says nothing. coward.",
  "confidence is being wrong at a volume nobody wants to argue with.",
  "the road to success is closed. take the sewer. everyone does. nobody mentions it.",
  "you have never once seen your own spine. trust issues start at home.",
  "if life gives you lemons, someone is watching you and they know which house.",
  "be the reason a stranger checks their smoke alarm tonight.",
  "your body is a temple, structurally condemned, still open to the public.",
  "success is failure that got away with it.",
  "the mitochondria is the powerhouse of the cell and it has never once helped you emotionally.",
  "drink water. not that water. you know which water. we both do.",
  "you were the sperm that won. that's the last competition you entered voluntarily.",
  "sometimes the universe closes a door, and sometimes it keeps opening the wrong drawer forever.",
  "nobody is coming to save you. someone is coming. not to save you.",
  "live each day like your landlord is inside the walls.",
  "growth is uncomfortable, which is why tumors are so confident.",
  "if you can't beat them, join them. if you can't join them, they're a family.",
  "every problem has a solution and every solution has a smell.",
  "your gut is your second brain, which explains everything about both of them.",
  "a wise man drank the bathwater once and said nothing about it for forty years.",
  "you are exactly as real as the guy in your dream who had a job.",
  "be someone your dog would still bite, but respectfully.",
  "rock bottom has a gift shop and you already own everything in it.",
  "the early bird gets the worm. the late bird gets whatever the worm was on.",
  "manifest your dreams. the universe is legally required to ignore you, but try.",
  "teeth are just bones that got out and made something of themselves.",
  "god is real and he's on his phone.",
  "the universe has a plan for you and most of it is filler.",
  "somewhere a star exploded so you could be mildly disappointed on a tuesday.",
  "heaven has a waitlist. you're not on it. you're on a different list.",
  "the meaning of life was found in 1974 and immediately lost again.",
  "god made you in his image, rotated it ninety degrees, and walked away.",
  "everyone dies. some people also have to move apartments first.",
  "you will die and the group chat will continue without you, briefly, then also die.",
  "death is nature's way of telling you to slow down, permanently, with authority.",
  "one day you'll be a skeleton and nobody will ask about your goals.",
  "a crow remembers your face. a crow does not care about your face. be the crow.",
  "somewhere a possum is having a better week than you and it lives in a wall.",
  "pigeons have no plan and total confidence. this is the model.",
  "a wasp has never doubted itself once and look what it's doing with that.",
  "be like the goose: unemployed, aggressive, beloved.",
  "dolphins are intelligent and they do crimes. intelligence is not a direction.",
  "your eyes are wet cameras your mother installed and never updated.",
  "you are a sock full of soup with opinions.",
  "under your face is a skull that has never smiled once.",
  "blood is supposed to stay inside. that's most of the job.",
  "you grew those hands from nothing and you use them to scroll. nature is patient.",
  "gas station sushi believed in itself and look where that got everybody.",
  "expired mayonnaise is still mayonnaise, legally, in spirit.",
  "eat clean, sleep well, and stop licking things in parking lots.",
  "the gas station hot dog has been turning for eleven years. that's discipline.",
  "studies show four in three people cannot be trusted with numbers.",
  "ninety-seven percent of statistics are invented by a man named trevor. trevor is also invented.",
  "you are in the top one percent of people reading this exact sentence. enjoy the prize.",
  "the key to happiness is routine, consistency, and never opening that cabinet again.",
  "life is like a box of chocolates and someone's finger is in it.",
  "follow your dreams until they lead into the woods, then stop. obviously stop.",
  "be present. be grateful. be quiet. there's something in the vents.",
  "you are doing your best and your best is absolute dogshit. growth!",
  "nobody gives a fuck, and that's the most freedom anyone will ever hand you.",
  "some days you're the hammer, some days the thumb, most days just fucking damp.",
  "fuck it. that's the whole philosophy. it scales beautifully.",
  "your feelings are valid and also completely fucking useless right now.",
  "believe in yourself. hr already stopped.",
  "nobody is irreplaceable, said the man being replaced, into a box.",
  "work smarter, not harder, and eventually not at all, like a rock.",
  "your worth is not your productivity. your worth is also not anything else. great news.",
  "be the ceo of your own life. embezzle from yourself. nobody checks.",
  "there is no 'i' in team, but there is 'meat', and that's the part they wanted.",
  "never trust a man with clean shoes and a clear plan. he's holding.",
  "they can't arrest you for thoughts yet, allegedly, in most counties.",
  "ketamine is not a personality but it is a schedule.",
  "if you're the smartest person in the room, check the room for gas.",
  "crime doesn't pay but it doesn't invoice either, so it stays competitive.",
  "everything is legal until somebody writes it down.",
  "your record is clean because nobody was looking. stay humble.",
  "the second mouse gets the cheese. the third mouse gets questioned.",
  "you can't pour from an empty cup, but you can throw the cup.",
  "somewhere out there is a version of you who folded the laundry. he is not better. he is just folded.",
  "comparison is the thief of joy. raccoons are the thief of everything else.",
  "discipline is doing what needs doing while damp and furious.",
  "every accomplishment begins with the decision to stand up, which is where most of them end.",
  "stars can't shine without darkness. bulbs can. be a bulb. bulbs have it figured out.",
  "you miss one hundred percent of the buses you scream at.",
  "do it scared. do it wet. do it in the wrong order and blame the weather.",
  "there is a light at the end of the tunnel and it is a man with a flashlight and questions.",
  "the tallest tree catches the most wind, the most lightning, and eventually the most chainsaw.",
  "bloom where you're planted, unless you were planted in a parking lot, in which case sue.",
  "some people meditate. some people scream into a towel. the towel is faster.",
  "you are not behind. there is no schedule. there is, however, a man with a clipboard, and he disagrees.",
  "chase your dreams. they're faster than you, and they know it, and they're enjoying this.",
  "a river cuts through rock because the rock had no lawyer.",
  "fall seven times, stand up eight, get counted as a medical event.",
  "nothing is impossible. some things are just extremely illegal and poorly attended.",
  "you are the author of your own story, which explains the tense problems.",
  "turn your wounds into wisdom, or into a limp people ask about at parties.",
  "everything happens for a reason and the reason is usually that nobody checked.",
  "the universe is expanding, mostly to get away from this.",
  "your intuition is your body's way of guessing loudly.",
  "hard work beats talent when talent is asleep in a van somewhere, which it is.",
  "a goal without a plan is a wish. a plan without a goal is a tuesday. both end the same.",
  "never look back unless you hear it again.",
  "you have one life. statistically that's the correct amount. any more would be greedy.",
  "the obstacle is the way. the obstacle is also on fire. reconsider the way.",
  "be the change you wish to see in the world, then move before anyone traces it.",
  "every ending is a new beginning, except the last one, which is just an ending.",
  "silence is golden. screaming is free. budget accordingly.",
  "your comfort zone has excellent lighting and one exit, which is bricked.",
  "you cannot control the wind. you can, however, blame it, loudly, for years.",
  "there are no bad ideas in brainstorming, which is how we got most of history.",
  "the first step is admitting you have a problem. the second step is naming it after a friend.",
  "you are enough. not for that, obviously. but generally. loosely. in a legal sense.",
  "trust the process. the process is three guys and a spreadsheet and one of them is lying.",
  "whatever doesn't kill you gives it another go later with better information.",
  "everybody's got a plan until the plan makes eye contact.",
  "you're not lost. you're just extremely committed to this hallway.",
  "the grass is greener where the dog goes. think about that. then don't.",
  "being an adult is saying 'after this week it calms down' until the funeral.",
  "your future self is watching and taking absolutely no notes.",
  "you have survived every single worst day so far, which is statistically suspicious. who's helping you.",
  "wake up. show up. throw up. repeat as scheduled.",
  "do one thing every day that scares you, ideally by accident, ideally near a hospital.",
  "motivation is temporary. damage is structural.",
  "the best time to plant a tree was twenty years ago. the second best time is when nobody's watching your yard.",
  "you can't unring a bell but you can absolutely eat one.",
  "some doors close so others can open, and one of them is a fridge, and you're already in front of it.",
  "the cave you fear to enter holds your treasure and also whatever made that noise.",
  "life is short and wide and slightly sticky.",
  "be humble. you are seventy percent water and none of it is yours.",
  "everyone you meet is fighting a battle you know nothing about, mostly with a printer.",
  "kindness costs nothing, which is exactly what it's worth on the open market.",
  "throw kindness around like confetti, then spend four years finding it in the carpet.",
  "you are somebody's reason to smile. it's about that thing you did. they remember. they talk about it.",
  "a candle loses nothing by lighting another candle except its entire competitive advantage.",
  "give a man a fish and he eats for a day. teach a man to fish and he reschedules twice and asks for the fish.",
  "the only way out is through, and there's a toll, and it's cash, and there's no machine.",
  "rome wasn't built in a day but it burned in about four, so pace is a scam.",
  "history repeats itself because nobody was taking attendance the first time.",
  "those who cannot remember the past are absolutely thriving.",
  "the pen is mightier than the sword, which is why they took the pen.",
  "knowledge is power, power corrupts, so study hard and become a menace.",
  "absorb what is useful, discard what is not, and stop chewing the useful parts.",
  "simplicity is the ultimate sophistication, said a man with eleven assistants.",
  "perfection is the enemy of done. done is the enemy of thursday. thursday has no enemies. be thursday.",
  "fake it till you make it, then keep faking it, because apparently nobody built the real part.",
  "dress for the job you want, which explains the man in the wizard hat at the bank.",
  "the customer is always right, which is why civilization is like this.",
  "networking is just haunting a room until somebody hires you to leave.",
  "your resume is a work of fiction and your interview is the audiobook.",
  "under promise, over deliver, then lie down in the dark and vibrate.",
  "there's no traffic on the extra mile because there's no road, no water, and no signal.",
  "quiet quitting is just employment with the sound off.",
  "money can't buy happiness but it does buy the absence of several specific screams.",
  "a budget tells your money where to go. yours filed a missing persons report and moved on.",
  "invest early, invest often, and never ask what the man in the vest is doing with it.",
  "the fastest way to double your money is to fold it. financial advice is everywhere and none of it is supervised.",
  "buy low, sell high, and stop crying in the parking lot of the bank.",
  "you are one decision away from a completely different life and about forty from lunch.",
  "somewhere between 'i can't' and 'i did' is a long damp stretch of 'i'm doing it tuesday'.",
  "don't tell people your plans. show them your results. failing that, show them nothing and move house.",
  "winners never quit and quitters never win, but leavers get out clean and nobody talks about the leavers.",
  "aim for the moon. if you miss you'll be in space, which is worse, and colder, and permanent.",
  "the sky is not the limit. the sky is where the air stops. that is very much a limit.",
  "shoot your shot. retrieve your shot. apologize for your shot.",
  "great things never came from comfort zones, but neither did most of the ambulances.",
  "your only competition is yourself, and he's cheating, and he started earlier.",
  "be so good they can't ignore you, or so damp they can't approach you.",
  "the world needs your light, on a dimmer, from another room.",
  "consistency beats intensity, which is why the drip beats the flood and the mold beats them both.",
  "one percent better every day compounds into one exhausted animal in a year.",
  "small steps every day. that's just walking. you've been doing it. congratulations on walking.",
  "habits are the compound interest of self-improvement, and yours are accruing against you.",
  "you don't rise to the level of your goals, you fall to the level of your systems, and your systems are a drawer.",
  "discipline equals freedom, and freedom equals nobody being available to help you.",
  "wake up at five a.m. nothing happens. do it again. that's the secret.",
  "cold showers build character. so does warmth. character is unfalsifiable.",
  "journaling is just leaving evidence.",
  "meditation is sitting still until the thoughts get bored and leave. they do not get bored.",
  "gratitude turns what you have into enough, which is very convenient for whoever gave you it.",
  "self care is a bath, a candle, and ignoring a letter for eleven weeks.",
  "set boundaries. enforce boundaries. move the boundaries at night so nobody can map them.",
  "protect your peace. whatever's left of it. put it in a tin.",
  "let go of what no longer serves you: grudges, fear, and that drawer of cables from 2011.",
  "detach from outcomes. attach to snacks. snacks have never lied to you.",
  "romanticize your life. then reread it. then panic quietly.",
  "you can't heal in the same environment that made you sick, but the rent there is unbeatable.",
  "therapy is expensive and screaming in a car is free, but only one of them scales.",
  "nobody is thinking about you. this is either freedom or a diagnosis.",
  "your inner child wants ice cream. your inner adult wants a nap. your inner landlord wants rent.",
  "talk to yourself like someone you love, which for most of you is a downgrade.",
  "be your own best friend. lower your standards for friends.",
  "you are not your thoughts. you are the wet thing behind them, taking notes.",
  "feel the feeling, name the feeling, and then put the feeling in the shed.",
  "it's okay to not be okay. it's also mandatory. there is no form to fill in.",
  "healing isn't linear. nothing is linear. stop drawing lines.",
  "some people are so poor all they have is money, and honestly, they're managing.",
  "comparison is a thief and a liar and it lives in your phone and you pay its rent.",
  "delete the app. reinstall the app. this is the cycle of life and it has no exit.",
  "your screen time report is a confession and it's notarized.",
  "touch grass. not that grass. that grass belongs to a man.",
  "log off. go outside. regret it immediately. return with information.",
  "the algorithm knows you better than your mother and it has never asked how you are.",
  "be authentic online, where it is impossible to be authentic, and monetize that.",
  "everyone is faking it and the ones who look calm are faking it hardest and possibly medicated.",
  "nobody has any idea what they're doing. some of them have a lanyard.",
  "adults are just tall children with debt and a favorite mug.",
  "growing up is realizing the grown ups were also guessing, loudly, near heavy machinery.",
  "your parents did their best, and their best was a coin flip and a casserole.",
  "family is who shows up. nobody showed up. interesting.",
  "blood is thicker than water, and also harder to get out of things.",
  "you can't choose your family but you can absolutely stop answering the phone.",
  "forgive them. not out loud. not to their face. just internally, resentfully, forever.",
  "holding a grudge is like carrying a hot coal, except the coal is fun and you've named it.",
  "time heals all wounds and causes most of them, so it's basically a subscription.",
  "closure is a myth invented by people who got closure.",
  "love is friendship on fire, which is also a description of a crime scene.",
  "communication is key. so is the actual key. neither of you has either.",
  "if they wanted to, they would. they didn't. that's the whole text.",
  "never chase, never beg, and never explain why you're on the roof.",
  "you'll find love when you stop looking, and also when you stop being like this.",
  "everyone has a soulmate and yours is probably a horse in another country.",
  "relationships are about compromise, which means both people are slightly wrong forever, on purpose.",
  "marriage is two people agreeing to be confused in the same building.",
  "communicate your needs. then lower your needs. then discard the needs. serenity.",
  "the one that got away got away for a reason and the reason is on your file.",
  "somebody out there is looking for exactly what you have to offer, and they are very lost.",
  "you are a catch. you are a catch in the way a cold is a catch.",
  "be single. be free. be the guy talking to the dog at the party.",
  "confidence is silent. insecurity is loud. both of them are wet.",
  "dress how you want, live how you want, and stop explaining the hat.",
  "beauty is on the inside, which is where everything alarming also lives.",
  "you look great. someone should have told you sooner. nobody was going to.",
  "age is just a number, specifically the number of years you have been decomposing on schedule.",
  "you're not old, you're vintage, which means you cost more and work less.",
  "growing older is a privilege denied to many, which is not the comfort they think it is.",
  "wrinkles are just laughter that stayed. so is the twitch.",
  "grey hair is earned. bald is achieved. both are unrelated to effort.",
  "your body is not a machine, it is a rented shed with feelings.",
  "listen to your body. your body is a liar with excellent delivery.",
  "stretch. not because it helps. because the alternative is what's happening now.",
  "exercise releases endorphins, and also releases whatever that noise was.",
  "no pain no gain, which is why nobody has ever gained anything from a nap, except everything.",
  "the gym is a building where people pay to lift things they then put back.",
  "abs are made in the kitchen, which is also where they are quietly destroyed.",
  "you don't need motivation, you need a routine, a system, and someone to take your phone.",
  "sleep is the best meditation and the worst hobby and the only one that's free.",
  "eight hours of sleep, three litres of water, and one long unanswered question at 3 a.m.",
  "nothing good happens after 2 a.m., and nothing at all happens before 10.",
  "naps are just short deaths you get to review afterwards.",
  "you can sleep when you're dead, which is soon, so pace it.",
  "the bags under your eyes are luggage from a trip you don't remember booking.",
  "coffee is a personality, a religion, and a legal stimulant, and you owe it everything.",
  "rise and grind, or rise and lie back down, which is also technically a rise.",
  "mondays are a construct. so are tuesdays. so is the ceiling, honestly, if you think about load bearing.",
  "the week has seven days and four of them are just wednesday with a wig.",
  "tomorrow is the busiest day of the week, judging by what you've filed there.",
  "someday is not a day of the week, which is why nothing is ever there when you look.",
  "do it now. later is a place where things go to be forgotten with dignity.",
  "procrastination is just doing the side quests until the main quest expires.",
  "you're not procrastinating, you're marinating, and you have been marinating since march.",
  "deadlines are the only true motivator and they know it and they're smug about it.",
  "there's no such thing as writer's block, only a chair you don't respect.",
  "done is better than perfect. abandoned is better than both and much faster.",
  "start before you're ready. you will never be ready. readiness was discontinued.",
  "everything you want is on the other side of fear, behind a paywall, in a queue.",
  "fear is a liar with excellent production values and a full crew.",
  "courage is not the absence of fear, it's fear that got tired and stopped arguing.",
  "feel the fear and do it anyway. feel the fear and go home. the fear is constant. the fear is the only constant.",
  "anxiety is just excitement without permission.",
  "worrying is like paying interest on a debt that hasn't been invented yet.",
  "overthinking is thinking with the brakes cut.",
  "what if it all works out? then what? have you planned for that? you haven't. that's the real fear.",
  "the best revenge is massive success. the second best is a slightly better fence.",
  "prove them wrong, or prove them right in an unexpected way and confuse everybody.",
  "living well is the best revenge, which is unfortunate, because you've seen the rates.",
  "success is the best revenge and silence is the best success and neither is available to you at this volume.",
  "some people will hate you for no reason, and some for excellent, well documented reasons.",
  "not everyone will like you. you're not soup. even soup has critics. nobody is safe.",
  "haters are just fans with a different subscription tier.",
  "if they talk about you behind your back, they're behind you, and that's tactically poor.",
  "be so busy improving yourself that you have no time to criticize others, or breathe, or eat.",
  "rise above it. then look down at it. then keep looking. that's the reward.",
  "the best apology is changed behavior. the second best is moving away.",
  "own your mistakes. frame them. charge admission.",
  "learn from failure, because failure is the only teacher who's always available and never calls in sick.",
  "there's no failure, only feedback, delivered at volumes ranging from whisper to fire alarm.",
  "fail fast, fail often, fail in a way that generates a small insurance payout.",
  "every master was once a disaster, and some of them stayed, and they're doing fine.",
  "you learn more from losing than winning, which is great, because look at this.",
  "experience is what you get when you didn't get what you wanted, plus a rash.",
  "mistakes are proof you're trying. so is the noise. so is the smell.",
  "the expert in anything was once a beginner who didn't know when to leave.",
  "practice makes perfect, and perfect makes insufferable, and insufferable makes money.",
  "ten thousand hours of anything makes you strange about it.",
  "comparison is the thief of joy but competition is the thief of everything else including your afternoon.",
  "stay in your lane. widen your lane. repaint the lane at night. nobody can stop you.",
  "bloom in your own time, at your own pace, alone, unsupervised, in the dark.",
  "everyone's timeline is different and yours has a gap nobody will explain.",
  "it's never too late to start over, though it is getting quite late, and people are leaving.",
  "you're not starting over, you're starting with experience and a limp.",
  "plot twist: nothing changes and you're fine with it and that's the ending.",
  "every day is a fresh start, which is why every day is exhausting.",
  "new year, new me, same skeleton, same drawer of cables.",
  "resolutions are just wishes with a deadline and a witness.",
  "this is your sign. it doesn't say anything. it's just a sign. you asked for a sign.",
  "the universe is sending you a message and the message is 'seen'.",
  "everything is figureoutable, except printers, and one specific hinge.",
  "there's a solution to every problem, and for several problems, the solution is a bucket.",
  "when one door closes another opens, but the hallway is where you actually live now.",
  "if it's meant to be it will be, which is a comforting way of saying nobody's driving.",
  "what's for you won't pass you, mostly because it's slow and doesn't know where you are.",
  "trust the timing of your life. the timing is not trustworthy. the timing has a record.",
  "everything is temporary except the group chat and the mould.",
  "this too shall pass. it may pass like a kidney stone. it shall, however, pass.",
  "nothing lasts forever, except that one email, which will outlive us all.",
  "you are exactly where you need to be, according to your gps, which has been wrong before, near water.",
  "life happens for you, not to you, unless you check the paperwork, in which case, to you.",
  "the struggle ends when gratitude begins, or when the deadline passes, whichever's louder.",
  "pain is inevitable, suffering is optional, and the paperwork is mandatory.",
  "you can't have a rainbow without rain, a permit, and someone willing to stand in it.",
  "storms make trees take deeper roots, or fall directly onto a shed. nature runs both programs.",
  "after every storm comes a rainbow, and after that, an assessor.",
  "be the calm in the storm, or be the storm, or be the man who bolted the shed properly in march. be that man.",
  "bad things happen to good people, and to bad people, and to sheds. it's not personal. it's not anything.",
  "karma isn't real but consequences have excellent aim.",
  "what goes around comes around, slower than advertised, and to the wrong address.",
  "the universe balances everything eventually, using methods nobody would sign off on.",
  "everything evens out in the end, said the man, evenly, in the end.",
  "there's a reason for everything, and it's usually that a guy named dave signed something in 1994.",
  "you get one life and one body and neither came with a manual or a receipt.",
  "nobody gets out of this alive, and the ones who look like they will are lying.",
  "memento mori, which is latin for 'the fridge is making that noise again'.",
  "you will be forgotten, which is the good news, and the bad news is not yet.",
  "in a hundred years nobody will remember this, which is also true of everything you've ever been proud of.",
  "the graveyard is full of indispensable men and one guy who was genuinely quite useful.",
  "live like you're dying, which you are, at the standard rate.",
  "your obituary will be four lines and one of them will be wrong.",
  "legacy is what you leave behind, which for most people is a shed full of paint.",
  "they say you die twice: once when you stop breathing, and once when the group chat goes quiet.",
  "somewhere your future grave is just grass, minding its business, waiting, patient, employed.",
  "the clock is ticking, and the clock has never once been asked to stop, and would not.",
  "time is money, money is fake, therefore time is fake, therefore you're not late.",
  "you have all the time in the world and none of it is convenient.",
  "there's never enough time, except in dentist waiting rooms, where there is infinite time.",
  "the days are long but the years are short and the wednesdays are eternal.",
  "yesterday is history, tomorrow is a mystery, today is under investigation.",
  "live in the moment. the moment is damp. live in it anyway.",
  "be here now. be here later. be here indefinitely. there's no bus.",
  "the present is a gift, which is why you can't return it.",
  "stop and smell the roses, then stop and identify what's underneath the roses.",
  "take the scenic route. get lost. meet a man named barry. this is what living is.",
  "not all who wander are lost. some are being followed, respectfully, at a distance.",
  "adventure awaits and has not confirmed a time, a place, or its intentions.",
  "travel broadens the mind and narrows the wallet and widens the general sense of doom.",
  "collect moments, not things, except snacks, blankets, and one reliable torch.",
  "say yes to everything, then read what you signed, then move country.",
  "life begins at the end of your comfort zone, and so does most of the litigation.",
  "jump and the net will appear, is a thing said exclusively by people who own nets.",
  "leap of faith is just falling with branding.",
  "take risks. not that one. any of the others. not that one either.",
  "fortune favors the bold, and insurance favors the specific.",
  "go big or go home, and honestly home is nice, home has a chair.",
  "you only regret the chances you didn't take, and about nine that you did, and one enormously.",
  "in twenty years you won't remember this, unless you do it, in which case it's all anyone will discuss.",
  "do it for the story. the story is not going to be good. do it anyway.",
  "one day this will all be a funny anecdote told by somebody else, inaccurately.",
  "you'll laugh about this later, in a room, with professionals.",
  "it's not a mistake, it's a plot development, and the writers have given up.",
  "everything is content, which is why nothing is sacred and everything is damp.",
  "turn your mess into a message, then a merch line, then a scandal.",
  "your struggle is somebody's inspiration and somebody else's screenshot.",
  "be somebody's reason to believe, ideally in something small and achievable, like doors.",
  "lead by example. any example. there's no quality control on examples.",
  "a leader is someone who walks in front and hopes very hard.",
  "great leaders listen, then do what they were going to do, but slower, with eye contact.",
  "delegation is trusting someone else to ruin it in a new and educational way.",
  "teamwork makes the dream work, and the dream is a spreadsheet, and nobody's opened it.",
  "surround yourself with people who lift you up, physically, in case of stairs.",
  "you are the average of the five people you spend the most time with, and one of them is a dog.",
  "your network is your net worth, which is why you're like this.",
  "it's not who you know, it's who knows what you did.",
  "show up early, stay late, and eventually live there, quietly, undetected.",
  "the harder you work the luckier you get, which is a thing luck has never confirmed.",
  "nothing worth having comes easy, except naps, which arrive uninvited and take everything.",
  "good things come to those who wait, and better things to those who take, and nothing at all to those who ask.",
  "patience is a virtue and virtue is unpaid.",
  "slow and steady wins the race, and then is immediately questioned about the other tortoise.",
  "the tortoise won because the hare had other things going on, emotionally.",
  "there's no shortcut to anywhere worth going, which is why nobody is anywhere.",
  "it's a marathon, not a sprint, and you did not sign up for either, and there's a number on your shirt.",
  "pace yourself. nobody knows the distance. there is no distance. stop running.",
  "rest is productive, which is the single greatest thing anyone has ever gotten away with saying.",
  "you are not a machine. machines get maintenance. you get a weekend.",
  "burnout is your body's way of filing a complaint through the only channel available.",
  "take a break before you become one.",
  "you can do anything but not everything, and not that, and probably not now.",
  "saying no is a complete sentence, and a complete personality, and eventually a complete isolation.",
  "protect your energy. bottle it. sell it. retire.",
  "boundaries are just fences with better marketing.",
  "not my circus, not my monkeys, not my building, not my problem, not my footprints.",
  "you can't set yourself on fire to keep others warm, though several people have tried and the data is compelling.",
  "pour into your own cup first, then look inside your cup, then reconsider the whole system.",
  "fill your own cup. empty your own cup. lose the cup. achieve peace.",
  "selfish is just self-preservation with bad pr.",
  "you don't owe anyone anything, legally speaking, in some jurisdictions, temporarily.",
  "let people misunderstand you. it's cheaper and takes less time.",
  "explaining yourself is a full time job with no benefits and a hostile client base.",
  "be misunderstood by many rather than understood by a committee.",
  "not everyone will get you, and one or two will get you far too well, and that's worse.",
  "the right people will find you, eventually, probably at the wrong time, definitely without notice.",
  "you attract what you are, which explains an enormous amount, on reflection, unfortunately.",
  "like attracts like, which is why the group chat is like that.",
  "energy doesn't lie, but it does exaggerate, and it does drink.",
  "trust your gut, unless your gut has been wrong before, which it has, extensively, on record.",
  "follow your heart, bring your brain, and leave the pancreas out of this entirely.",
  "your heart wants what it wants and your heart has never once been right about anything.",
  "listen to your inner voice. interrogate your inner voice. where was your inner voice in 2019.",
  "the answers are within you, badly filed, in a language you no longer speak.",
  "you already know what to do. that's the worst part. that's always been the worst part.",
  "doing the right thing is simple, unpopular, unpaid, and generally unwitnessed.",
  "character is who you are when nobody's watching, which is why you're eating that standing up.",
  "integrity is doing the right thing even when it costs you, which is how you can tell it's real and why nobody has it.",
  "be honest. be kind. be quiet about the honest parts.",
  "honesty is the best policy, and the worst hobby, and an appalling opening line.",
  "the truth will set you free, and then it will follow you, and it will bring friends.",
  "the truth hurts, but so does everything, so it's not a good filter.",
  "speak your truth, then move house, then change your name, then speak it again.",
  "not everything needs to be said. almost nothing needs to be said. say nothing. achieve everything.",
  "silence can't be misquoted, which is the only real security available to you.",
  "think before you speak, then think again, then eat something instead.",
  "it's better to remain silent and be thought a fool than to speak and be recorded.",
  "a closed mouth gathers no foot, and also no friends, and eventually no invitations.",
  "choose your words carefully. they're the only ones you get and they're all secondhand.",
  "words have power, which is why they should be kept in a drawer.",
  "you can't take back words, though you can absolutely take back most objects.",
  "sticks and stones break bones, and words break the other thing, and both take about six weeks.",
  "be gentle with yourself. you're doing this for the first time and you've clearly not read anything.",
  "you're not behind, you're not late, you're just wet and slightly early for something worse.",
  "give yourself grace, because nobody else has any and the shops are shut.",
  "you survived the day. that's the whole assignment. that was always the whole assignment.",
  "getting out of bed counts. staying out is extra credit.",
  "some days you thrive and some days you just prevent things and both are wins.",
  "doing nothing is doing something, and doing something is often much worse.",
  "the bar is on the floor and you have cleared it, magnificently, by existing.",
  "lower the bar. bury the bar. deny the bar was ever installed.",
  "progress not perfection, attendance not progress, presence not attendance, breathing not presence. keep going down.",
  "you don't have to be great, you just have to be there, and honestly, not even that.",
  "show up as you are, damp and unprepared, like everyone else, who are also lying about it.",
  "bring your whole self to work, then watch them regret asking.",
  "authenticity is just admitting it out loud before somebody finds out.",
  "be yourself, unless you can be a horse, in which case reconsider everything immediately.",
  "be yourself. everyone else is taken, and doing considerably better with it.",
  "nobody can be you, which is either a compliment or a containment strategy.",
  "you're one in a million, which means there are eight thousand of you, and they've formed a group.",
  "you are unique, like everyone who has ever said that, in that exact order, with that exact face.",
  "there's only one you, thank god, said the universe, quickly, and moved on.",
  "you were made from stardust, which is mostly carbon and disappointment and one heavy metal.",
  "you are the universe experiencing itself, badly, on a tuesday, near a bin.",
  "we are all just atoms pretending to have thursdays.",
  "you are ninety-nine percent empty space, which explains the acoustics.",
  "every atom in your body was forged in a dying star, and now they're doing this.",
  "the same water that was in a dinosaur is in you now, and it's not impressed either.",
  "everything you touch was touched before by something with worse hygiene and better prospects.",
  "the sun will explode eventually and it hasn't told anyone the date.",
  "space is silent, infinite, and completely uninterested in your quarterly review.",
  "the universe is expanding and it is not waiting for you to be ready.",
  "there are more stars than grains of sand, and none of them know your name, and that's the good news.",
  "somewhere out there is intelligent life and it has decided against contact, and it was right.",
  "the earth is spinning at a thousand miles an hour and you're the one who's tired.",
  "gravity is holding you down and it's the only thing that's ever been consistent about you.",
  "physics doesn't care about your feelings, and neither does the second step, which is broken.",
  "entropy always wins, which is why your kitchen looks like that and it's not your fault.",
  "everything tends toward chaos, and your job is to be surprised by this daily.",
  "the universe is under no obligation to make sense to you, and has never pretended otherwise.",
  "nothing means anything and that's why you can do whatever you want, within reason, near the shops.",
  "life has no meaning, so you get to make one up, and yours can be about snacks.",
  "the meaning of life is the search for the meaning of life, which is a scam invented by searchers.",
  "you are free, which is terrifying, and there is no supervisor, and that's the whole problem.",
  "nobody's in charge. nobody has ever been in charge. please stop asking who's in charge.",
  "there's no adult in the room. you are the adult in the room. that's the emergency.",
  "the system is broken, was never built, and is currently being invoiced.",
  "everything is made up and the points don't matter and yet somehow there is rent.",
  "money isn't real, time isn't real, but the letter is real and it's on the table.",
  "society is a group hallucination with excellent plumbing.",
  "civilization is four hot meals away from the shed and everyone knows it.",
  "the whole world is held together by three people and none of them are answering.",
  "somebody, somewhere, is making all this up as they go, and doing worse than you'd think.",
  "every institution is just people, which is the single most frightening sentence available.",
  "question everything, then get tired, then accept most of it, then question the rest at 3 a.m.",
  "think for yourself. everybody else is thinking for themselves too and look at this.",
  "common sense is neither, and has never been located.",
  "trust the experts, doubt the experts, become an expert, doubt yourself, retire.",
  "nobody knows anything, but some of them know it in a font.",
  "the more you know the less you know, until eventually you know nothing and get promoted.",
  "wisdom is knowing how little you know and charging for it anyway.",
  "certainty is a symptom, not an achievement.",
  "strong opinions, loosely held, wetly delivered.",
  "the dumbest people are the most confident, which raises questions about how you're feeling right now.",
  "if you're not embarrassed by who you were a year ago, you weren't paying attention, or you were asleep.",
  "you'll cringe at this version of yourself too, and that version will cringe at that one, forever, downward.",
  "growth means outgrowing people, chairs, and several previously reasonable positions.",
  "change is the only constant, and it never sends a schedule, and it always arrives during dinner.",
  "adapt or die, and honestly the second one requires less admin.",
  "be like water, formless, adaptable, and eventually inside the walls.",
  "bend so you don't break, then keep bending, then discover the new shape is permanent.",
  "the bamboo bends, the oak resists, the shed is quietly the strongest structure on the property.",
  "flexibility is just weakness that worked out.",
  "fall down seven times, get up eight, get a stern letter from someone's insurer.",
  "resilience is just repeated exposure with a nicer word for it.",
  "you are stronger than you think, which is lucky, because you're going to need every bit of it and then a bit more.",
  "you can handle more than you think, which is exactly why it keeps getting sent to you.",
  "god gives the hardest battles to his strongest soldiers, which is a terrible management strategy.",
  "the strongest people are the ones who had no other option, and no receipt, and no help.",
  "what doesn't kill you makes you funnier at parties and worse at sleeping.",
  "every scar is a story and some of the stories are just 'i was carrying too much at once'.",
  "broken crayons still color, but nobody reaches for them, and that's the actual lesson.",
  "the cracks are where the light gets in, and the damp, and eventually the surveyor.",
  "kintsugi is japanese for 'we're keeping the broken one and charging extra'.",
  "you're not broken, you're just assembled optimistically.",
  "some assembly required, and the instructions were in another box, and the box is gone.",
  "you came with no manual, no warranty, and one small bag of extra screws nobody can account for.",
  "you are a work in progress and the progress is unclear and the work is unpaid.",
  "you are both a masterpiece and a mess, and the gallery wants an answer by friday.",
  "perfectly imperfect, structurally questionable, currently upright.",
  "nobody's perfect, and the ones who look it are running a very expensive operation.",
  "comparison is the thief of joy and the landlord of everything else.",
  "you're not competing with anyone, which is convenient, because you'd lose.",
  "run your own race, at your own pace, in your own direction, away from the race.",
  "the only person you should compare yourself to is yesterday's you, who was also having a nightmare.",
  "beat your personal best, or match it, or acknowledge it politely from a distance.",
  "every day above ground is a good day, said a man with a very low bar and a shovel.",
  "it could always be worse, and it's actively working on it, and it has resources.",
  "someone has it worse, which has never once helped anybody, and yet here we are.",
  "perspective is realizing your problem is small and also that small problems still ruin tuesdays.",
  "count your blessings. use a spreadsheet. audit annually. prepare for questions.",
  "gratitude is remembering the good things while the bad things wait politely.",
  "be thankful for what you have before it becomes what you had and then what you talk about.",
  "you'll miss this one day, which is the most sinister sentence in the language.",
  "one day you'll look back on this and realize it was the good part. it's not. but you will.",
  "these are the days you'll remember, unfortunately, in detail, at inconvenient hours.",
  "enjoy the little things, for one day you'll look back and realize they were invoices.",
  "happiness is not a destination, it's a brief clerical error.",
  "happiness is wanting what you have, which is why the marketing industry works so hard.",
  "the secret to happiness is low expectations and a reliable chair.",
  "choose happy, which is a choice available to almost nobody, but do go on.",
  "fake a smile until it's real, then keep faking it, because the real one is worse.",
  "laughter is the best medicine, which explains the state of the healthcare system.",
  "smile, it confuses people, and confusion is a tactical advantage.",
  "a day without laughter is a day wasted, and a day with laughter is also mostly wasted, but pleasantly.",
  "life's too short to be serious, and far too long to be like this.",
  "don't take life too seriously, nobody gets out anyway, and the exit is unmarked.",
  "we're all just here, damp and temporary, doing our best impression of people with plans.",
  "in the end we're all just stories, and most of them need editing, and one needs burning.",
  "nothing matters, so everything's allowed, within reason, near the shops, before six.",
  "you're going to be fine. not good. fine. fine is the whole product.",
  "it works out or it doesn't, and either way there's thursday.",
  "everything will be okay in the end, and if it's not, then it's not the end, or the definition of okay needs revisiting.",
  "you've got this. you do not have this. nobody has this. there is no this.",
  "keep going. there's no reason. that's not a requirement. just keep going.",
  "glow like the sun to plow like my son",
  "imagine a pencis, heck, imagine two pencils",
  "even something has meth in it",
  "are you sure youre awake right now?",
  "getting slapped is something can be done by a stranger, use this opportunity",
  "ants dont feel what you feel",
  "I C U P N i forgot what i had else to say",
  "being terminally online is not as bad as being terminally online and losing",
  "have you tried to eat a spoon? anyways you should",
  "youre fueled by motivation, im fueled by whatever this is. were not the same",
  "its already to late to start, just go eat socks at this point",
  "youre as orange as a banana",
  "heard of H2O? now prepare for the upgrade H2O2",
  "the walls are mad at you",
  "banging rocks is not as amusing as you make it look",
  "soda can fix any problem, especially if its something electrical",
  "this app was made just to make you think if humanity actually evolving backwards",
  "youre such a fool, that fools gold is just gold for you",
  "look someone in the eyes and tell them that you ate the spoiled cheese",
  "problems are problems only if we dont ignore them",
  "your phone doesnt feel very comfy with all it seen",
  "its not 'bad smell' its your alpha aura, keep going champ",
  "bob can be your friend if you accept the terms",
  "today is a good day to start collecting jars",
  "uhhhhhhh well i dont know what to tell you",
  "never mind the hour, it changes all the time anyways",
  "you should be a sleeper agent, getting paid to sleep is cool",
  "you can never face west because its on your left",
  "when even was the last time you ate a bug?",
  "while reading this you became an npc, congratulations",
  "dont work hard, get hard while working, its boosts morale",
  "dont hide your freak the government already know about it anyways",
  "restart your phone for a complete waste of time",
  "its time to buy A.I powered electrical jars",
  "the taste of regret is plain, but it gets better if you add salt to it",
  "did you try turning it off and on again? how about setting it on fire?",
  "people say gambling is bad because they wanna hog it for themselves",
  "start hogging all the air, become a monopoly",
  "if day drinking is so bad then why did god invent it?",
  "the sun is hot",
  "always click on suspicious links! the FOMO is real",
  "go outside and apologize to a tree, it knows what you did",
  "try standing in a corner for no reason, see who breaks first",
  "eat a rock. small one. start small, thats just good practice",
  "lick a battery for science, then stop, then dont do it again",
  "have you considered simply not? anyways youre gonna",
  "put your phone in rice. nothing is wrong with it. just do it",
  "go stare at a wall until it blinks first, thats the whole game",
  "try walking backwards to work, the commute is the same length",
  "start every sentence with 'legally speaking' and watch things improve",
  "put on two hats. no reason. just see how it feels",
  "go press a random button somewhere, be the reason something beeps",
  "try holding your breath until someone notices, could be a while",
  "stand up right now. sit back down. thats cardio, technically",
  "go outside and look confused, someone will eventually help",
  "clap once for no reason and let everyone deal with it",
  "whisper your plans to a spoon, spoons dont talk",
  "try eating soup with a fork, character is built in the small moments",
  "go knock on your own door, see if youre home",
  "put a chair on a table. dont explain. leave",
  "try to fold a fitted sheet, fail, understand the universe better",
  "the walls heard everything and theyre processing it",
  "your ceiling has opinions about you and none of them are kind",
  "the fridge knows how many times you opened it for nothing",
  "your chair has held you longer than most people have, respect that",
  "the floor is doing all the work and gets none of the credit",
  "your shoes have been everywhere you have and never complained once",
  "the microwave counts down from thirty and judges you the whole time",
  "your keyboard is tired and its not gonna say anything about it",
  "the toaster remembers. the toaster always remembers",
  "your mirror is not lying, its just not being helpful about it",
  "the stairs are keeping track and youre behind",
  "your washing machine ate that sock on purpose, it had reasons",
  "the ceiling fan has seen things and continues spinning anyways, be that",
  "your desk lamp has watched your worst hours and stayed on",
  "the door handle knows exactly how hard you pulled when it said push",
  "heard of sleep? try the premium version, unconsciousness",
  "water is just soup that gave up before it started",
  "you know oxygen? theres a stronger one but you cant handle it",
  "gravity is optional but nobody has read the manual",
  "heard of monday? theres a worse one coming and its unnamed",
  "salt is just rock you were allowed to eat, think about the others",
  "heard of walking? try it faster, thats called running, its worse",
  "the human body is seventy percent water and thirty percent excuses",
  "scientists confirmed that thing you thought, they just wont say which",
  "studies show that studies show things, and thats the whole finding",
  "they found a new color but youre not cleared for it",
  "the number between six and seven was removed for safety reasons",
  "heard of gravity? now prepare for the sequel, falling",
  "they upgraded time but only for people who wake up early",
  "scientifically youre mostly bacteria wearing a hoodie",
  "are you sure you locked it? are you sure you have a door?",
  "did you actually wake up today or is this the other thing",
  "how do you know youre reading this and not remembering it",
  "you blinked and missed something important, it wasnt this",
  "quick, whats behind you. dont look. just know",
  "you have never seen your own face, only pictures of it, sit with that",
  "nobody has ever seen you and them at the same time. suspicious",
  "this might be a dream but the rent is real either way",
  "are you the same person who started reading this sentence",
  "you dont remember most of your life and youre fine with that somehow",
  "time only moves when youre watching, thats why nothing gets done",
  "if a tree falls and youre not there, thats none of your business",
  "never read the terms, they only get worse if you understand them",
  "click every popup, some of them are lonely",
  "reply all. always reply all. be the change",
  "never save your work, live with intensity",
  "if you dont look at the bill it cant hurt you, thats how bills work",
  "answer unknown numbers, could be your destiny, probably a scam, could be both",
  "never charge above eighty percent, keep it exciting",
  "delete a random file today, keep the computer humble",
  "say yes before you hear the question, thats how adventures start",
  "lend money to someone you barely like, see what happens",
  "never label anything, mystery keeps a kitchen alive",
  "skip the tutorial, learn through suffering like the ancients",
  "agree to the meeting, then simply do not attend, revolutionary",
  "put it in the drawer. the drawer solves everything eventually",
  "if it smells fine its fine, thats a rule and its yours now",
  "this app has no purpose and neither does the guy who opened it",
  "you installed this. voluntarily. nobody made you",
  "this notification cost more effort than it looks and its still this",
  "congratulations you have reached the part where nothing happens",
  "this message was generated by absolutely nobody with any qualifications",
  "we could have said something useful here but we didnt",
  "this is the free version, the paid version is also this",
  "if this app made you think, thats a bug and we're aware",
  "press shuffle again, its the only thing either of us can control",
  "you came here for wisdom and got whatever this is, no refunds",
  "this text was reviewed by zero people and shipped anyways",
  "somebody wrote this at an unreasonable hour and youre paying for it now",
  "there is no algorithm here, just vibes and poor judgement",
  "you are the seventh person to read this exact sentence today, probably",
  "this app knows nothing about you and still has notes",
  "you became an npc somewhere around 2019 and nobody told you",
  "your search history is a cry for help written in fragments",
  "the algorithm gave up on you and started guessing",
  "being online is just being wet in a different way",
  "you have opinions about people who do not know you exist",
  "log off. dont log off. the outcome is identical",
  "your screen time is a number and that number has feelings about you",
  "you scrolled past something important eleven minutes ago, its gone now",
  "somewhere a server is storing that thing you typed and deleted",
  "you have watched four hundred hours of people doing things you will not do",
  "the internet was a mistake and youre one of the load bearing parts",
  "touch grass, or dont, grass has never once helped anybody specifically",
  "your notifications are just other people's problems arriving on schedule",
  "you are one bad post away from a completely different life, aim carefully",
  "ants have a whole thing going on and youre not part of it",
  "birds are just dinosaurs that downsized, respect the pivot",
  "a snail has a house and no job, think about that arrangement",
  "crows can hold a grudge for years, thats commitment youll never have",
  "somewhere a fish is having a completely normal day, unaffected",
  "cows have best friends. you have a group chat. its not the same",
  "a moth will die for a lightbulb, thats more conviction than youve shown all year",
  "pigeons have never once checked if theyre welcome, be a pigeon",
  "a jellyfish has no brain and its been here longer than all of us",
  "bees have a job and a house and a queen and you have neither",
  "squirrels bury food and forget where, thats basically your savings account",
  "a cat has decided things about you and will never elaborate",
  "worms are just tubes that made it work, and honestly, good for them",
  "the goose does not negotiate. the goose has never negotiated",
  "somewhere a spider built something better than anything you made this year",
  "the early bird gets the worm and the worm gets nothing, be neither",
  "a journey of a thousand miles starts with looking for your keys",
  "they say time heals everything but they never say how long, thats the trick",
  "what doesnt kill you tries again next tuesday, its patient",
  "the grass is greener over there because thats where the drain is",
  "you cant step in the same river twice but you can absolutely fall in once",
  "when life gives you lemons that means life knows where you live",
  "the first pancake is always ruined and so is the first everything",
  "they say listen to your heart but your heart is just a wet pump with opinions",
  "rome wasnt built in a day, it was built by people who are all dead now",
  "the pen is mightier than the sword until somebody brings a sword",
  "actions speak louder than words which is why nobody hears anything",
  "an apple a day keeps nothing away, apples have no power",
  "good things come to those who wait and also to those who dont, its random",
  "you cant judge a book by its cover but you can absolutely judge a person by their van",
  "anyways",
  "thats it. thats the message",
  "i had something for this",
  "forget it, its gone",
  "nevermind, wrong notification",
  "we ran out of ideas around here somewhere",
  "hm",
  "actually you know what, dont worry about it",
  "there was a point to this earlier",
  "this one didnt work out, we'll get the next one",
  "skip this one, its not our best",
  "honestly? no idea",
  "we thought this would land better than it did",
  "pretend this was profound and move on with your day",
  "just imagine something inspiring here",
  "the sun is far away and hot",
  "water is wet and thats been confirmed",
  "bread is just flat food that got ambitious",
  "the ocean is large and mostly unsupervised",
  "most doors open. some do not. thats the whole system",
  "your bones are inside you right now, all of them",
  "there are more chairs than people and nobody talks about it",
  "clouds are just water taking a break above everyone",
  "a wall is a floor that refused",
  "soup is a drink you eat, and nobody has explained that",
  "there is a country you will never think about again after this",
  "most sand was a rock once, thats a rough career",
  "cheese is milk that was left alone too long and became someone",
  "every road goes somewhere, technically, eventually, roughly",
  "the moon has been up there this whole time doing nothing",
  "you should be a sleeper agent, the benefits are unclear but the hours are great",
  "get a job where nobody knows what you do, thats the real career",
  "your boss also has a boss and that guy is also confused",
  "work smart, not hard, or dont work, thats also an option people forget",
  "start a business selling nothing, the overhead is incredible",
  "become a consultant, nobody has ever checked what that means",
  "invest in jars. i wont explain. jars",
  "money is fake but the machine that takes it is very real",
  "your salary is a number someone guessed in a meeting you werent in",
  "put it on the card, future you is a completely different guy anyways",
  "the economy is three people and a spreadsheet and one of them is guessing",
  "you could quit right now. you wont. but you could. thats freedom",
  "become a monopoly on something nobody wants, no competition at all",
  "charge for it. whatever it is. charge for it",
  "every job is just moving things or telling people to move things",
  "your body makes so much stuff and you asked for none of it",
  "you shed a whole layer of yourself constantly and never notice",
  "theres a version of you made entirely of the hair youve lost",
  "your stomach makes noises at strangers and you cannot stop it",
  "you have eaten several spiders and youll never know which nights",
  "everyone is slightly damp all the time and we agreed not to mention it",
  "your feet have been carrying you for years with zero recognition",
  "you blink constantly and see none of the gaps, thats a cover up",
  "theres stuff in your teeth right now, statistically",
  "you produce a shocking amount of liquid for a thing that looks dry",
  "your nose is always in your vision and your brain deleted it for you",
  "you have never once heard your real voice and thats a mercy",
  "the government knows your snack schedule and finds it concerning",
  "they moved something last night and youll notice in about a week",
  "theres a room where they decide the names of colors and youre not in it",
  "someone approved this and that person walks among us",
  "they changed it and pretended it was always like that, and it worked",
  "there is a list and youre on it, middle of the list, unremarkable",
  "the man in the van is not watching you, hes eating, hes on break",
  "they know. they dont care. thats the twist",
  "somebody has your password and theyre disappointed by what they found",
  "there is a guy whose whole job is deciding when the lights flicker",
  "steve can be your emergency contact if you agree to the arrangement",
  "by reading this you have entered a contract, its mostly fine",
  "you agreed to something in 2014 and its still running in the background",
  "the terms changed. they always change. nobody has ever read them",
  "you have unknowingly subscribed to something and it renews soon",
  "press and hold to opt out. dont let go. ever",
  "your free trial of being okay expires at some point today",
  "youre doing great, comparatively, against a very low bar, held by us",
  "believe in yourself, someone has to, and it wont be the bank",
  "youre not a failure, youre a prototype nobody funded",
  "you have so much potential and its just sitting there getting older",
  "today could be your day. it wont be. but it could",
  "youre one of a kind and thats not necessarily the compliment you want",
  "keep going champ, the finish line was moved but keep going",
  "proud of you. not for anything specific. just generally, vaguely",
  "you tried, and thats the part nobody can take from you, mostly because nobody wants it",
  "youre the main character of a show that got cancelled after one season",
  "nobody can do it like you, which is why they asked somebody else",
  "you got this. we checked. you dont. but you got something",
  "look at you, upright, functioning, mostly, still here",
  "you are exactly enough for a task that has not been assigned yet",
  "celebrate the small wins because the large ones are running late",
  "start collecting bottle caps, no reason, become known for it",
  "today is a good day to begin hoarding batteries you will never test",
  "collect receipts. not for taxes. just to have them",
  "start a rock collection, they were free and now theyre yours",
  "begin gathering keys that open nothing, build the mystery",
  "collect other peoples pens, its already happening, lean in",
  "gather one of every fork, the set will never be complete, thats the point",
  "start saving jars now, you'll understand later, or you wont",
  "gas station food has never once claimed to be safe, thats honesty",
  "the sandwich you didnt eat is haunting a fridge somewhere",
  "cereal is soup, sandwich is a wrap, everything is one of five things",
  "eat the thing in the back of the fridge, take the risk, be legendary",
  "expired is a suggestion written by a man who has never been hungry",
  "your fridge has three foods and eleven condiments, thats a lifestyle",
  "drink water. you havent. we can tell. everyone can tell",
  "coffee is just bean water and it runs the entire planet",
  "you have eaten the same six meals for years and called it variety",
  "microwave it twice, the first time was a warmup for both of you",
  "never mind the day, they keep making new ones",
  "its later than you think and earlier than youd like",
  "tomorrow is just today with more evidence against you",
  "the week has too many days and none of them are load bearing",
  "you have been alive for a lot of minutes and remember four of them",
  "the clock is a suggestion and everyone agreed to take it seriously",
  "time passes whether you do the thing or not, thats the free part",
  "its already too late to start, which means the pressure is off, enjoy",
  "an hour is only sixty minutes but it doesnt always feel legal",
  "you will never get this moment back and honestly you can have it",
  "treat yourself. with what. we dont know. treat yourself",
  "take a bath. stay in it. become the bath",
  "self care is turning your phone off and immediately turning it on",
  "go to bed early, lie there, achieve nothing, it still counts",
  "drink water, touch grass, eat a rock, standard routine",
  "your feelings are valid and also nobody asked and both are true",
  "rest is productive which is the greatest lie ever successfully told",
  "cry it out, then hydrate, thats just physics",
  "meditation is sitting still while your brain screams, and you win by waiting",
  "lower your standards until you meet them, thats called achievement",
  "anyways good luck with everything, all of it, generally",
  "go do something. or dont. we're not the boss of you. nobody is",
  "see you tomorrow, or later today, we schedule these randomly",
  "thats all we had. genuinely. thats the whole thing",
  "okay bye",
];
