// All quotes for Sheetposo. Lowercase deadpan nonsense — absurd instructions,
// objects with feelings, fake science, anticlimax. English only.
//
// The original generated batch was dropped; what remains is the wtf pack and
// everything written from it, plus the lines Tomer wrote himself.
//
// Authored lowercase so notification bodies read as casual as the poster does
// (the poster also lowercases at render time).
//
// ADDING QUOTES — the house rule:
//   Write the whole line lowercase. Do not capitalise the first letter here.
//   formatQuote() below capitalises it at display time, for the poster, the
//   seen list, and the notification body alike. Hand-casing the list would
//   only make it inconsistent.
//   Deliberate capitals mid-line are fine and are left alone — e.g. the
//   "I C U P" gag depends on them.
//
// Bumping QUOTES_VERSION invalidates quote indexes in already-scheduled
// notifications and forces an immediate reschedule, so the list can be freely
// rewritten, reordered, or trimmed.
export const QUOTES_VERSION = 4;

// The single place a quote is turned into something readable. Everything that
// shows a quote to a person goes through this, so the casing can never drift
// between the poster and the notification.
export function formatQuote(text) {
  if (typeof text !== "string" || !text) return "";
  return text.charAt(0).toUpperCase() + text.slice(1);
}

export const QUOTES = [
  "feeling proud? remember that even toilet water is drinkable.",
  "parents are like drugs, you flush them down the toilet when the cops arrive.",
  "doing things wrong is easy, doing things the worst way is a challenge.",
  "glow like the sun to plow like my son",
  "imagine a pencis, heck, imagine two pencils",
  "even something has meth in it",
  "are you sure youre awake right now?",
  "getting slapped is something can be done by a stranger, use this opportunity",
  "ants dont feel what you feel",
  "I C U P N i forgot what i had else to say",
  "being terminally online is not as bad as being terminally online and losing",
  "have you tried to eat a spoon? anyways you should",
  "youre fueled by motivation, im fueled by whatever this is. were not the same",
  "its already to late to start, just go eat socks at this point",
  "youre as orange as a banana",
  "heard of H2O? now prepare for the upgrade H2O2",
  "the walls are mad at you",
  "banging rocks is not as amusing as you make it look",
  "soda can fix any problem, especially if its something electrical",
  "this app was made just to make you think if humanity actually evolving backwards",
  "youre such a fool, that fools gold is just gold for you",
  "look someone in the eyes and tell them that you ate the spoiled cheese",
  "problems are problems only if we dont ignore them",
  "your phone doesnt feel very comfy with all it seen",
  "its not 'bad smell' its your alpha aura, keep going champ",
  "bob can be your friend if you accept the terms",
  "today is a good day to start collecting jars",
  "uhhhhhhh well i dont know what to tell you",
  "never mind the hour, it changes all the time anyways",
  "you should be a sleeper agent, getting paid to sleep is cool",
  "you can never face west because its on your left",
  "when even was the last time you ate a bug?",
  "while reading this you became an npc, congratulations",
  "dont work hard, get hard while working, its boosts morale",
  "dont hide your freak the government already know about it anyways",
  "restart your phone for a complete waste of time",
  "its time to buy A.I powered electrical jars",
  "the taste of regret is plain, but it gets better if you add salt to it",
  "did you try turning it off and on again? how about setting it on fire?",
  "people say gambling is bad because they wanna hog it for themselves",
  "start hogging all the air, become a monopoly",
  "if day drinking is so bad then why did god invent it?",
  "the sun is hot",
  "always click on suspicious links! the FOMO is real",
  "go outside and apologize to a tree, it knows what you did",
  "try standing in a corner for no reason, see who breaks first",
  "eat a rock. small one. start small, thats just good practice",
  "lick a battery for science, then stop, then dont do it again",
  "have you considered simply not? anyways youre gonna",
  "put your phone in rice. nothing is wrong with it. just do it",
  "go stare at a wall until it blinks first, thats the whole game",
  "try walking backwards to work, the commute is the same length",
  "start every sentence with 'legally speaking' and watch things improve",
  "put on two hats. no reason. just see how it feels",
  "go press a random button somewhere, be the reason something beeps",
  "try holding your breath until someone notices, could be a while",
  "stand up right now. sit back down. thats cardio, technically",
  "go outside and look confused, someone will eventually help",
  "clap once for no reason and let everyone deal with it",
  "whisper your plans to a spoon, spoons dont talk",
  "try eating soup with a fork, character is built in the small moments",
  "go knock on your own door, see if youre home",
  "put a chair on a table. dont explain. leave",
  "try to fold a fitted sheet, fail, understand the universe better",
  "the walls heard everything and theyre processing it",
  "your ceiling has opinions about you and none of them are kind",
  "the fridge knows how many times you opened it for nothing",
  "your chair has held you longer than most people have, respect that",
  "the floor is doing all the work and gets none of the credit",
  "your shoes have been everywhere you have and never complained once",
  "the microwave counts down from thirty and judges you the whole time",
  "your keyboard is tired and its not gonna say anything about it",
  "the toaster remembers. the toaster always remembers",
  "your mirror is not lying, its just not being helpful about it",
  "the stairs are keeping track and youre behind",
  "your washing machine ate that sock on purpose, it had reasons",
  "the ceiling fan has seen things and continues spinning anyways, be that",
  "your desk lamp has watched your worst hours and stayed on",
  "the door handle knows exactly how hard you pulled when it said push",
  "heard of sleep? try the premium version, unconsciousness",
  "water is just soup that gave up before it started",
  "you know oxygen? theres a stronger one but you cant handle it",
  "gravity is optional but nobody has read the manual",
  "heard of monday? theres a worse one coming and its unnamed",
  "salt is just rock you were allowed to eat, think about the others",
  "heard of walking? try it faster, thats called running, its worse",
  "the human body is seventy percent water and thirty percent excuses",
  "scientists confirmed that thing you thought, they just wont say which",
  "studies show that studies show things, and thats the whole finding",
  "they found a new color but youre not cleared for it",
  "the number between six and seven was removed for safety reasons",
  "heard of gravity? now prepare for the sequel, falling",
  "they upgraded time but only for people who wake up early",
  "scientifically youre mostly bacteria wearing a hoodie",
  "are you sure you locked it? are you sure you have a door?",
  "did you actually wake up today or is this the other thing",
  "how do you know youre reading this and not remembering it",
  "you blinked and missed something important, it wasnt this",
  "quick, whats behind you. dont look. just know",
  "you have never seen your own face, only pictures of it, sit with that",
  "nobody has ever seen you and them at the same time. suspicious",
  "this might be a dream but the rent is real either way",
  "are you the same person who started reading this sentence",
  "you dont remember most of your life and youre fine with that somehow",
  "time only moves when youre watching, thats why nothing gets done",
  "if a tree falls and youre not there, thats none of your business",
  "never read the terms, they only get worse if you understand them",
  "click every popup, some of them are lonely",
  "reply all. always reply all. be the change",
  "never save your work, live with intensity",
  "if you dont look at the bill it cant hurt you, thats how bills work",
  "answer unknown numbers, could be your destiny, probably a scam, could be both",
  "never charge above eighty percent, keep it exciting",
  "delete a random file today, keep the computer humble",
  "say yes before you hear the question, thats how adventures start",
  "lend money to someone you barely like, see what happens",
  "never label anything, mystery keeps a kitchen alive",
  "skip the tutorial, learn through suffering like the ancients",
  "agree to the meeting, then simply do not attend, revolutionary",
  "put it in the drawer. the drawer solves everything eventually",
  "if it smells fine its fine, thats a rule and its yours now",
  "this app has no purpose and neither does the guy who opened it",
  "you installed this. voluntarily. nobody made you",
  "this notification cost more effort than it looks and its still this",
  "congratulations you have reached the part where nothing happens",
  "this message was generated by absolutely nobody with any qualifications",
  "we could have said something useful here but we didnt",
  "this is the free version, the paid version is also this",
  "if this app made you think, thats a bug and we're aware",
  "press shuffle again, its the only thing either of us can control",
  "you came here for wisdom and got whatever this is, no refunds",
  "this text was reviewed by zero people and shipped anyways",
  "somebody wrote this at an unreasonable hour and youre paying for it now",
  "there is no algorithm here, just vibes and poor judgement",
  "you are the seventh person to read this exact sentence today, probably",
  "this app knows nothing about you and still has notes",
  "you became an npc somewhere around 2019 and nobody told you",
  "your search history is a cry for help written in fragments",
  "the algorithm gave up on you and started guessing",
  "being online is just being wet in a different way",
  "you have opinions about people who do not know you exist",
  "log off. dont log off. the outcome is identical",
  "your screen time is a number and that number has feelings about you",
  "you scrolled past something important eleven minutes ago, its gone now",
  "somewhere a server is storing that thing you typed and deleted",
  "you have watched four hundred hours of people doing things you will not do",
  "the internet was a mistake and youre one of the load bearing parts",
  "touch grass, or dont, grass has never once helped anybody specifically",
  "your notifications are just other people's problems arriving on schedule",
  "you are one bad post away from a completely different life, aim carefully",
  "ants have a whole thing going on and youre not part of it",
  "birds are just dinosaurs that downsized, respect the pivot",
  "a snail has a house and no job, think about that arrangement",
  "crows can hold a grudge for years, thats commitment youll never have",
  "somewhere a fish is having a completely normal day, unaffected",
  "cows have best friends. you have a group chat. its not the same",
  "a moth will die for a lightbulb, thats more conviction than youve shown all year",
  "pigeons have never once checked if theyre welcome, be a pigeon",
  "a jellyfish has no brain and its been here longer than all of us",
  "bees have a job and a house and a queen and you have neither",
  "squirrels bury food and forget where, thats basically your savings account",
  "a cat has decided things about you and will never elaborate",
  "worms are just tubes that made it work, and honestly, good for them",
  "the goose does not negotiate. the goose has never negotiated",
  "somewhere a spider built something better than anything you made this year",
  "the early bird gets the worm and the worm gets nothing, be neither",
  "a journey of a thousand miles starts with looking for your keys",
  "they say time heals everything but they never say how long, thats the trick",
  "what doesnt kill you tries again next tuesday, its patient",
  "the grass is greener over there because thats where the drain is",
  "you cant step in the same river twice but you can absolutely fall in once",
  "when life gives you lemons that means life knows where you live",
  "the first pancake is always ruined and so is the first everything",
  "they say listen to your heart but your heart is just a wet pump with opinions",
  "rome wasnt built in a day, it was built by people who are all dead now",
  "the pen is mightier than the sword until somebody brings a sword",
  "actions speak louder than words which is why nobody hears anything",
  "an apple a day keeps nothing away, apples have no power",
  "good things come to those who wait and also to those who dont, its random",
  "you cant judge a book by its cover but you can absolutely judge a person by their van",
  "anyways",
  "thats it. thats the message",
  "i had something for this",
  "forget it, its gone",
  "nevermind, wrong notification",
  "we ran out of ideas around here somewhere",
  "hm",
  "actually you know what, dont worry about it",
  "there was a point to this earlier",
  "this one didnt work out, we'll get the next one",
  "skip this one, its not our best",
  "honestly? no idea",
  "we thought this would land better than it did",
  "pretend this was profound and move on with your day",
  "just imagine something inspiring here",
  "the sun is far away and hot",
  "water is wet and thats been confirmed",
  "bread is just flat food that got ambitious",
  "the ocean is large and mostly unsupervised",
  "most doors open. some do not. thats the whole system",
  "your bones are inside you right now, all of them",
  "there are more chairs than people and nobody talks about it",
  "clouds are just water taking a break above everyone",
  "a wall is a floor that refused",
  "soup is a drink you eat, and nobody has explained that",
  "there is a country you will never think about again after this",
  "most sand was a rock once, thats a rough career",
  "cheese is milk that was left alone too long and became someone",
  "every road goes somewhere, technically, eventually, roughly",
  "the moon has been up there this whole time doing nothing",
  "you should be a sleeper agent, the benefits are unclear but the hours are great",
  "get a job where nobody knows what you do, thats the real career",
  "your boss also has a boss and that guy is also confused",
  "work smart, not hard, or dont work, thats also an option people forget",
  "start a business selling nothing, the overhead is incredible",
  "become a consultant, nobody has ever checked what that means",
  "invest in jars. i wont explain. jars",
  "money is fake but the machine that takes it is very real",
  "your salary is a number someone guessed in a meeting you werent in",
  "put it on the card, future you is a completely different guy anyways",
  "the economy is three people and a spreadsheet and one of them is guessing",
  "you could quit right now. you wont. but you could. thats freedom",
  "become a monopoly on something nobody wants, no competition at all",
  "charge for it. whatever it is. charge for it",
  "every job is just moving things or telling people to move things",
  "your body makes so much stuff and you asked for none of it",
  "you shed a whole layer of yourself constantly and never notice",
  "theres a version of you made entirely of the hair youve lost",
  "your stomach makes noises at strangers and you cannot stop it",
  "you have eaten several spiders and youll never know which nights",
  "everyone is slightly damp all the time and we agreed not to mention it",
  "your feet have been carrying you for years with zero recognition",
  "you blink constantly and see none of the gaps, thats a cover up",
  "theres stuff in your teeth right now, statistically",
  "you produce a shocking amount of liquid for a thing that looks dry",
  "your nose is always in your vision and your brain deleted it for you",
  "you have never once heard your real voice and thats a mercy",
  "the government knows your snack schedule and finds it concerning",
  "they moved something last night and youll notice in about a week",
  "theres a room where they decide the names of colors and youre not in it",
  "someone approved this and that person walks among us",
  "they changed it and pretended it was always like that, and it worked",
  "there is a list and youre on it, middle of the list, unremarkable",
  "the man in the van is not watching you, hes eating, hes on break",
  "they know. they dont care. thats the twist",
  "somebody has your password and theyre disappointed by what they found",
  "there is a guy whose whole job is deciding when the lights flicker",
  "steve can be your emergency contact if you agree to the arrangement",
  "by reading this you have entered a contract, its mostly fine",
  "you agreed to something in 2014 and its still running in the background",
  "the terms changed. they always change. nobody has ever read them",
  "you have unknowingly subscribed to something and it renews soon",
  "press and hold to opt out. dont let go. ever",
  "your free trial of being okay expires at some point today",
  "youre doing great, comparatively, against a very low bar, held by us",
  "believe in yourself, someone has to, and it wont be the bank",
  "youre not a failure, youre a prototype nobody funded",
  "you have so much potential and its just sitting there getting older",
  "today could be your day. it wont be. but it could",
  "youre one of a kind and thats not necessarily the compliment you want",
  "keep going champ, the finish line was moved but keep going",
  "proud of you. not for anything specific. just generally, vaguely",
  "you tried, and thats the part nobody can take from you, mostly because nobody wants it",
  "youre the main character of a show that got cancelled after one season",
  "nobody can do it like you, which is why they asked somebody else",
  "you got this. we checked. you dont. but you got something",
  "look at you, upright, functioning, mostly, still here",
  "you are exactly enough for a task that has not been assigned yet",
  "celebrate the small wins because the large ones are running late",
  "start collecting bottle caps, no reason, become known for it",
  "today is a good day to begin hoarding batteries you will never test",
  "collect receipts. not for taxes. just to have them",
  "start a rock collection, they were free and now theyre yours",
  "begin gathering keys that open nothing, build the mystery",
  "collect other peoples pens, its already happening, lean in",
  "gather one of every fork, the set will never be complete, thats the point",
  "start saving jars now, you'll understand later, or you wont",
  "gas station food has never once claimed to be safe, thats honesty",
  "the sandwich you didnt eat is haunting a fridge somewhere",
  "cereal is soup, sandwich is a wrap, everything is one of five things",
  "eat the thing in the back of the fridge, take the risk, be legendary",
  "expired is a suggestion written by a man who has never been hungry",
  "your fridge has three foods and eleven condiments, thats a lifestyle",
  "drink water. you havent. we can tell. everyone can tell",
  "coffee is just bean water and it runs the entire planet",
  "you have eaten the same six meals for years and called it variety",
  "microwave it twice, the first time was a warmup for both of you",
  "never mind the day, they keep making new ones",
  "its later than you think and earlier than youd like",
  "tomorrow is just today with more evidence against you",
  "the week has too many days and none of them are load bearing",
  "you have been alive for a lot of minutes and remember four of them",
  "the clock is a suggestion and everyone agreed to take it seriously",
  "time passes whether you do the thing or not, thats the free part",
  "its already too late to start, which means the pressure is off, enjoy",
  "an hour is only sixty minutes but it doesnt always feel legal",
  "you will never get this moment back and honestly you can have it",
  "treat yourself. with what. we dont know. treat yourself",
  "take a bath. stay in it. become the bath",
  "self care is turning your phone off and immediately turning it on",
  "go to bed early, lie there, achieve nothing, it still counts",
  "drink water, touch grass, eat a rock, standard routine",
  "your feelings are valid and also nobody asked and both are true",
  "rest is productive which is the greatest lie ever successfully told",
  "cry it out, then hydrate, thats just physics",
  "meditation is sitting still while your brain screams, and you win by waiting",
  "lower your standards until you meet them, thats called achievement",
  "anyways good luck with everything, all of it, generally",
  "go do something. or dont. we're not the boss of you. nobody is",
  "see you tomorrow, or later today, we schedule these randomly",
  "thats all we had. genuinely. thats the whole thing",
  "okay bye",
];
